'use client';
import {AppSelect} from '@/components/ui/app-select';
import {useEffect,useMemo,useState} from 'react';
import {Plus,Trash2,Copy,Download,Wallet,ArrowDownLeft,ArrowUpRight} from 'lucide-react';
import {Adjustments,FinancialModel,Investment} from '@/types/model';
import {calculateFinancing,createInvestment} from '@/lib/investments';
import {NumberInput} from '@/components/ui/number-input';
import {downloadBlob} from '@/lib/export/excel';
import {modelMonthLabel} from '@/lib/model-calendar';
import {tr} from '@/lib/i18n';
const typeNames={annual:'Годовая ставка',fixed:'Доход за срок','profit-share':'Доля прибыли'};
function Numeric({label,value,onChange,max=1e12,min=0,hint}:{hint?:string;label:string;value:number;onChange:(n:number)=>void;max?:number;min?:number}){
 return <label className="v-field"><span>{label}</span><NumberInput aria-label={label} value={value} min={min} max={max} onChange={e=>onChange(Math.max(min,Math.min(max,+e.target.value)))}/>{hint&&<small>{hint}</small>}</label>;
}
export function InvestmentsView({model,a,onChange,initialProject=null}:{model:FinancialModel;a:Adjustments;onChange:(m:FinancialModel)=>void;initialProject?:string|null}){
 const [selected,setSelected]=useState(model.investments?.[0]?.id||''),[year,setYear]=useState(0),[table,setTable]=useState('portfolio');
 const investments=model.investments||[],inv=investments.find(i=>i.id===selected)||investments[0];
 const report=useMemo(()=>calculateFinancing(model,a),[model,a]);
 useEffect(()=>setYear(y=>Math.min(y,Math.ceil(report.months.length/12)-1)),[report.months.length]);
 const detail=report.investors.find(i=>i.investment.id===inv?.id);
 const fmt=(n:number)=>new Intl.NumberFormat('ru-RU',{style:'currency',currency:model.currency,maximumFractionDigits:0}).format(n);
 const save=(items:Investment[])=>onChange({...model,investments:items});
 const patch=(v:Partial<Investment>)=>inv&&save(investments.map(i=>i.id===inv.id?{...i,...v}:i));
 const add=()=>{const i=createInvestment(initialProject);save([...investments,i]);setSelected(i.id)};
 const labelMonth=(m:number)=>`М${m} · ${tr(modelMonthLabel(model.startDate,m))}`;
 const download=()=>{
  const rows=[['Месяц','Дата','Операционный поток','Взносы','Возврат капитала','Доход инвесторам','Итоговый поток','Накопленный поток','Остаток капитала','Остаток дохода'],...report.months.map(m=>[m.month,m.label,m.operatingNet,m.contribution,m.principalPaid,m.incomePaid,m.net,m.cumulative,m.principalBalance,m.incomeBalance])];
  const csv='\uFEFF'+rows.map(row=>row.map(x=>'"'+String(x).replaceAll('"','""')+'"').join(';')).join('\r\n');
  downloadBlob(new Blob([csv],{type:'text/csv;charset=utf-8'}),'investments-cash-flow.csv');
 };
 return <div className="investments-view"><div className="v-toolbar"><span>Все суммы в {model.currency} · Условия общие для сценариев · Взносы в начале месяца, выплаты в конце</span><div className="row"><button className="btn" onClick={download}><Download size={15}/>Скачать расчёт CSV</button><button className="btn dark" onClick={add}><Plus size={15}/>Добавить инвестора</button></div></div>
 <div className="v-kpis">{[['Привлечённый капитал',report.contributed,'Взносы, не выручка'],['Доход инвесторам',report.incomeAccrued,'Начисления за весь срок'],['Прибыль девелопера',report.developerProfit,`${(report.developerMargin*100).toFixed(1)}% от выручки после инвесторов`],['Дополнительный капитал',report.peak,report.peakMonth?labelMonth(report.peakMonth):'Дефицита нет']].map(([label,value,sub],i)=><section className={`v-kpi k${i===3?3:i}`} key={String(label)}><span>{label}</span><strong>{fmt(Number(value))}</strong><small>{sub}</small></section>)}</div>
 {!investments.length?<section className="v-card investment-empty"><Wallet size={36}/><h2>У каждого инвестора — свои условия</h2><p>Привяжите инвестицию к проекту или всему портфелю. Задайте взносы, способ начисления дохода и график возвратов.</p><div className="investment-types"><span>01 · Доля прибыли</span><span>02 · Годовая ставка</span><span>03 · Доход за срок</span></div><button className="btn dark" onClick={add}><Plus size={15}/>Создать первую инвестицию</button></section>:<>
 <div className="investment-tabs" role="tablist" aria-label="Инвесторы">{investments.map(i=><button role="tab" aria-selected={inv?.id===i.id} className={inv?.id===i.id?'active':''} key={i.id} onClick={()=>{setSelected(i.id);setYear(0)}}><b>{i.name||'Без названия'}</b><span>{typeNames[i.type]}{!i.enabled?' · выключен':''}</span></button>)}</div>
 {inv&&<div className="v-workgrid investment-editor"><section className="v-card"><div className="v-section-title"><div><span className="v-eyebrow">УСЛОВИЯ ДОГОВОРА</span><h2>Как зарабатывает инвестор</h2></div><label className="investment-toggle"><input type="checkbox" checked={inv.enabled} onChange={e=>patch({enabled:e.target.checked})}/>Включён в модель</label></div><div className="v-inputgrid"><label className="v-field"><span>Имя / название инвестора</span><input aria-label="Имя инвестора" value={inv.name} onChange={e=>patch({name:e.target.value})}/></label><label className="v-field"><span>Куда направлены инвестиции</span><AppSelect aria-label="Проект инвестиции" value={inv.projectId||'portfolio'} onChange={e=>patch({projectId:e.target.value==='portfolio'?null:e.target.value})}><option value="portfolio">Весь портфель</option>{model.projects.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</AppSelect></label><label className="v-field"><span>Тип доходности</span><AppSelect aria-label="Тип доходности" value={inv.type} onChange={e=>patch({type:e.target.value as Investment['type']})}><option value="annual">Годовая ставка</option><option value="fixed">Фиксированный % за срок</option><option value="profit-share">Доля от прибыли</option></AppSelect></label><Numeric label={inv.type==='annual'?'Номинальная ставка · % годовых':inv.type==='fixed'?'Доход на каждый взнос · % за весь срок':'Доля от положительной прибыли · %'} value={inv.rate} max={inv.type==='profit-share'?100:1000} onChange={rate=>patch({rate})}/>
 {inv.type==='annual'&&<><label className="v-field"><span>Начисление процентов</span><AppSelect aria-label="Начисление процентов" value={inv.compounding} onChange={e=>patch({compounding:e.target.value as Investment['compounding']})}><option value="simple">Простой · на остаток капитала</option><option value="monthly">Сложный · капитализация каждый месяц</option></AppSelect></label><label className="v-field"><span>Выплата начисленного дохода</span><AppSelect aria-label="Выплата дохода" value={inv.incomePayment} onChange={e=>patch({incomePayment:e.target.value as Investment['incomePayment']})}><option value="maturity">По графику + остаток при закрытии</option><option value="monthly">Ежемесячно весь начисленный доход</option></AppSelect></label></>}
 <Numeric label="Срок договора · месяц модели" value={inv.maturityMonth} min={1} max={720} onChange={maturityMonth=>patch({maturityMonth:Math.round(maturityMonth)})}/><label className="v-field"><span>Окончательный расчёт · {labelMonth(inv.maturityMonth)}</span><AppSelect aria-label="Окончательный расчёт" value={inv.autoSettle?'auto':'manual'} onChange={e=>patch({autoSettle:e.target.value==='auto'})}><option value="auto">Вернуть весь остаток в конце срока</option><option value="manual">Только заданные выплаты</option></AppSelect></label></div>
 <p className="v-note">{inv.type==='annual'?'Месячная ставка = годовая / 12. Частичный возврат в конце месяца уменьшает базу со следующего месяца. При капитализации проценты начисляются и на невыплаченный доход.':inv.type==='fixed'?'Процент применяется к каждому взносу один раз. Досрочный возврат капитала не уменьшает обещанный доход; меняется эффективная годовая доходность. Если доход должен зависеть от срока, используйте годовую ставку.':'Доля считается от положительной прибыли после фиксированной стоимости финансирования. Доли проектов распределяются первыми, доля портфеля — от оставшейся прибыли. При убытке доход равен нулю; возврат капитала всё равно моделируется по заданному графику.'}</p>
 <div className="v-shortcuts"><button className="btn" onClick={()=>{const copy={...structuredClone(inv),id:crypto.randomUUID(),name:inv.name+' · копия',enabled:false};save([...investments,copy]);setSelected(copy.id)}}><Copy size={14}/>Создать альтернативу</button><span className="v-note">Копия выключена, чтобы не удваивать финансирование.</span></div></section>
 <section className="v-card v-target"><span className="v-eyebrow">ЭКОНОМИКА ИНВЕСТОРА</span><h2>{inv.name||'Инвестор'}</h2>{detail?<><div className="v-goal"><span>Эффективная годовая доходность</span><strong>{detail.annualReturn===null?'—':detail.annualReturn.toFixed(2)+'%'}</strong><small>{detail.returnStatus}</small></div><div className="investment-summary">{[['Сумма вложений',detail.contributed],['Возврат капитала',detail.principalPaid],['Доход по договору',detail.incomeAccrued],['Выплата дохода',detail.incomePaid],['Невыплаченный капитал',detail.principalBalance],['Невыплаченный доход',detail.incomeBalance]].map(([label,value])=><div key={String(label)}><span>{label}</span><b>{fmt(Number(value))}</b></div>)}</div><p className="v-note">Годовая доходность рассчитана по датам взносов и выплат, а не делением общего процента на число лет. Это прогноз исполнения графика, не гарантированная доходность.</p></>:<p className="v-note">Инвестиция выключена или её проект не найден. Условия сохранены, но не участвуют в расчёте.</p>}</section></div>}
 {inv&&<section className="v-card"><div className="v-section-title"><div><span className="v-eyebrow">ГРАФИК ФИНАНСИРОВАНИЯ</span><h2>Взносы и частичные возвраты</h2></div></div><div className="investment-schedules"><div><h3><ArrowDownLeft size={16}/>Взносы инвестора</h3>{inv.tranches.map((t,idx)=><div className="investment-row" key={t.id}><Numeric label={`Взнос ${idx+1} · месяц`} hint={labelMonth(t.month)} min={1} max={720} value={t.month} onChange={month=>patch({tranches:inv.tranches.map(x=>x.id===t.id?{...x,month:Math.round(month)}:x)})}/><Numeric label={`Взнос ${idx+1} · сумма`} value={t.amount} onChange={amount=>patch({tranches:inv.tranches.map(x=>x.id===t.id?{...x,amount}:x)})}/><button className="icon-btn" aria-label={`Убрать взнос ${idx+1}`} onClick={()=>patch({tranches:inv.tranches.filter(x=>x.id!==t.id)})}><Trash2 size={15}/></button></div>)}<button className="btn" onClick={()=>patch({tranches:[...inv.tranches,{id:crypto.randomUUID(),month:1,amount:0}]})}><Plus size={14}/>Добавить взнос</button></div><div><h3><ArrowUpRight size={16}/>Возвраты инвестору</h3>{inv.repayments.map((t,idx)=><div className="investment-row repayment" key={t.id}><Numeric label={`Возврат ${idx+1} · месяц`} hint={labelMonth(t.month)} min={1} max={720} value={t.month} onChange={month=>patch({repayments:inv.repayments.map(x=>x.id===t.id?{...x,month:Math.round(month)}:x)})}/><Numeric label={`Возврат ${idx+1} · капитал`} value={t.principal} onChange={principal=>patch({repayments:inv.repayments.map(x=>x.id===t.id?{...x,principal}:x)})}/><Numeric label={`Возврат ${idx+1} · доход`} value={t.income} onChange={income=>patch({repayments:inv.repayments.map(x=>x.id===t.id?{...x,income}:x)})}/><button className="icon-btn" aria-label={`Убрать возврат ${idx+1}`} onClick={()=>patch({repayments:inv.repayments.filter(x=>x.id!==t.id)})}><Trash2 size={15}/></button></div>)}{!inv.repayments.length&&<p className="v-note">Частичных возвратов нет. {inv.autoSettle?'Капитал и доход будут выплачены в конце срока.':'Добавьте выплаты или включите окончательный расчёт.'}</p>}<button className="btn" onClick={()=>patch({repayments:[...inv.repayments,{id:crypto.randomUUID(),month:Math.min(inv.maturityMonth,12),principal:0,income:0}]})}><Plus size={14}/>Добавить возврат</button></div></div></section>}
 </>}
 <section className="v-card"><div className="v-section-title"><div><span className="v-eyebrow">ПО МЕСЯЦАМ</span><h2>Деньги после инвестиций</h2><p>Выплаты не ограничиваются остатком денег. Отрицательный накопленный поток показывает незакрытый дефицит.</p></div><div className="investment-table-controls"><AppSelect aria-label="Расчёт инвестиций" value={table} onChange={e=>setTable(e.target.value)}><option value="portfolio">Весь портфель</option>{detail&&<option value="investor">Выбранный инвестор</option>}</AppSelect><AppSelect aria-label="Период инвестиций" value={year} onChange={e=>setYear(+e.target.value)}>{Array.from({length:Math.ceil(report.months.length/12)},(_,i)=><option key={i} value={i}>М{i*12+1}–М{i*12+12}</option>)}</AppSelect></div></div><div className="table-scroll"><table className="v-months"><thead><tr><th>Показатель · {model.currency}</th>{report.months.slice(year*12,year*12+12).map(m=><th key={m.month}>{tr(m.label)}<small>М{m.month}</small></th>)}</tr></thead><tbody>{(table==='investor'&&detail?[
 ['Взносы','contribution'],['Возврат капитала','principalPaid'],['Начисленный доход','incomeAccrued'],['Выплаченный доход','incomePaid'],['Остаток капитала','principalBalance'],['Остаток дохода','incomeBalance']
 ]:[['Операционный поток','operatingNet'],['Взносы инвесторов','contribution'],['Возврат капитала','principalPaid'],['Доход инвесторам','incomePaid'],['Поток после инвестиций','net'],['Накопленный поток','cumulative'],['Остаток капитала','principalBalance'],['Невыплаченный доход','incomeBalance']]).map(([label,key])=><tr key={key}><th>{label}</th>{report.months.slice(year*12,year*12+12).map(m=>{const row=table==='investor'&&detail?detail.months[m.month-1]:m;const last=table==='investor'&&detail?detail.months.at(-1):undefined;const value=row?Number((row as unknown as Record<string,number>)[key]||0):key==='principalBalance'?last?.principalBalance||0:key==='incomeBalance'?last?.incomeBalance||0:0;return <td className={value<0?'negative':''} key={m.month}>{fmt(value)}</td>})}</tr>)}</tbody></table></div></section>
 {report.warnings.length>0&&<section className="v-card"><h2>Проверка условий</h2>{report.warnings.map((w,i)=><p key={i} className="v-warning investment-warning">{w}</p>)}</section>}
 <details className="v-card v-method"><summary>Как учитываются инвестиции</summary><p>Операционная выручка, затраты и маржа проекта остаются отдельными. Взнос и возврат капитала — финансирование. Годовые проценты и фиксированная доходность уменьшают прибыль после финансирования; доля прибыли — распределение остатка. Прибыль девелопера учитывает все начисленные доходы инвесторов, даже если выплаты ещё не запланированы.</p><p>Для доли проекта база включает его прямые и распределённые общие расходы, но не общефирменные расходы. Доля портфеля считается после всех операционных расходов, фиксированной стоимости финансирования и долей проектов. Доли одной базы складываются; превышение 100% показывается как ошибка, а не нормализуется.</p><p>Начальный остаток денег равен нулю. Взнос поступает в начале месяца. Проценты начисляются за месяц, затем происходят выплаты. Номинальная годовая ставка делится на 12; при ежемесячной капитализации проценты начисляются на капитал и невыплаченные проценты. Налоговая экономия от процентов, налоги инвестора, валютные разницы, юридические приоритеты и автоматическое списание капитала при убытке не моделируются.</p><p>XIRR использует даты начала / конца месяцев и ACT/365. Для неоднозначного потока с повторными вложениями после выплат показатель не выводится. Непогашенный остаток не считается выплатой инвестору. Условия договоров общие для сценариев; для сравнения разных условий используйте выключенные копии или снимки модели.</p><a href="https://www.investor.gov/financial-tools-calculators/calculators/compound-interest-calculator" target="_blank" rel="noreferrer">Сложный процент · Investor.gov</a></details>
 </div>;
}
