'use client';
import {InvestmentResult} from '@/lib/investments';
import {modelMonthLabel} from '@/lib/model-calendar';
import {tr} from '@/lib/i18n';
export function InvestmentOverview({investors,currency,startDate,onOpen,includesCompany}:{investors:InvestmentResult[];currency:string;startDate:string;onOpen:()=>void;includesCompany:boolean}){
 const fmt=(n:number)=>n.toLocaleString('ru-RU',{style:'currency',currency,maximumFractionDigits:0});
 const total=(key:'contributed'|'principalPaid'|'incomePaid'|'principalBalance'|'incomeBalance')=>investors.reduce((s,i)=>s+i[key],0);
 const payments=investors.flatMap(i=>i.months.filter(m=>m.principalPaid+m.incomePaid>0));
 const first=payments.length?Math.min(...payments.map(m=>m.month)):null,last=payments.length?Math.max(...payments.map(m=>m.month)):null;
 const date=(m:number)=>tr(modelMonthLabel(startDate,m));
 return <section className="v-card investment-overview" aria-label="Сводка по инвестициям"><span className="v-eyebrow">01 / ИНВЕСТИЦИИ</span><h2>Капитал и возвраты</h2><p className="v-note">{includesCompany?'Инвестиции модели':'Инвестиции, закреплённые за этим проектом'} · выбранный сценарий</p>{investors.length?<><div className="investment-overview-hero"><span>Всего привлечено по плану</span><strong>{fmt(total('contributed'))}</strong><small>{investors.length} договоров · за весь срок</small></div><div className="investment-summary"><div><span>Всего выплат по графику</span><b>{fmt(total('principalPaid')+total('incomePaid'))}</b></div><div><span>Доход инвесторам</span><b>{fmt(total('incomePaid'))}</b></div><div><span>Возврат капитала</span><b>{fmt(total('principalPaid'))}</b></div><div><span>Период выплат</span><b>{first!==null&&last!==null?`${date(first)} — ${date(last)}`:'Не задан'}</b></div></div>{total('principalBalance')+total('incomeBalance')>0&&<p className="notice">Не погашено по графику: {fmt(total('principalBalance')+total('incomeBalance'))}</p>}<div className="investment-overview-list">{investors.map(i=><div key={i.investment.id}><span><b>{i.investment.name||'Инвестор'}</b><small>{i.investment.rate}% {i.investment.type==='annual'?'годовых':i.investment.type==='fixed'?'за срок':'от прибыли'}{i.investment.type==='annual'?i.investment.compounding==='monthly'?' · сложный процент':' · простой процент':''}</small></span><span><b>{fmt(i.contributed)}</b><small>{i.equalPayment!==undefined?`${fmt(i.equalPayment)} / мес.`:'Индивидуальный график'}</small></span></div>)}</div></>:<div className="funding-empty"><strong>Инвестиции пока не добавлены</strong><p>Добавьте инвестора, сумму и условия — здесь появятся капитал, доход и сроки возврата.</p></div>}{!includesCompany&&<p className="v-note">Общие инвестиции портфеля здесь не распределяются.</p>}<button className="btn" onClick={onOpen}>{investors.length?'Условия и график выплат':'Добавить инвестицию'} ↗</button></section>;
}
