'use client';
import {AppSelect} from '@/components/ui/app-select';
import {useMemo,useState} from 'react';
import {FinancialModel,Adjustments} from '@/types/model';
import {portfolioSales,stressSales} from '@/lib/portfolio-sales';
import {calculatePortfolioCashFlow,timeline} from '@/lib/financial-engine';
import {modelMonthDate,modelMonthLabel} from '@/lib/model-calendar';
import {money,percent} from '@/lib/format';
import {tr,useLanguage} from '@/lib/i18n';
import {Field} from '@/components/ui/controls';
import {ProjectEditor} from '@/features/projects/project-editor';
import {copyModel} from '@/lib/copy-model';
import {useModels} from '@/store/model-store';

export function PortfolioPlan({model,a,onChange,notify}:{model:FinancialModel;a:Adjustments;onChange:(m:FinancialModel)=>void;notify:(s:string)=>void}){
 const {language}=useLanguage(),ru=language==='ru',t=(r:string,e:string)=>ru?r:e;
 const [capacity,setCapacity]=useState(4),[cashPercent,setCash]=useState(20),[down,setDown]=useState(30),[term,setTerm]=useState(12),[priceChange,setPrice]=useState(0),[year,setYear]=useState('all'),[preview,setPreview]=useState(false),[editing,setEditing]=useState<string|null>(null);
 const baseRows=useMemo(()=>portfolioSales(model,a),[model,a]);
 const projected=useMemo(()=>stressSales(model,a,{capacity,cashPercent,down,term,priceChange}),[model,a,capacity,cashPercent,down,term,priceChange]);
 const stressedRows=useMemo(()=>portfolioSales(projected,a),[projected,a]);
 const baseline=useMemo(()=>calculatePortfolioCashFlow(model,a),[model,a]),stress=useMemo(()=>calculatePortfolioCashFlow(projected,a),[projected,a]);
 const rows=preview?stressedRows:baseRows,end=Math.max(1,...baseRows.map(s=>s.month),...stressedRows.map(s=>s.month));
 const months=Array.from({length:end},(_,i)=>i+1),years=[...new Set(months.map(m=>modelMonthDate(model.startDate,m).getUTCFullYear()))];
 const visible=months.filter(m=>year==='all'||String(modelMonthDate(model.startDate,m).getUTCFullYear())===year);
 const count=(month:number,project?:string)=>rows.filter(s=>s.month===month&&(!project||s.projectId===project)).reduce((n,s)=>n+s.units,0);
 const cash=(month:number)=>rows.filter(s=>s.month===month&&s.tier.plan.type==='Full Cash').reduce((n,s)=>n+s.units,0);
 const selected=rows.filter(s=>visible.includes(s.month)),units=selected.reduce((n,s)=>n+s.units,0),cashUnits=selected.filter(s=>s.tier.plan.type==='Full Cash').reduce((n,s)=>n+s.units,0),value=selected.reduce((n,s)=>n+s.value,0),cashValue=selected.filter(s=>s.tier.plan.type==='Full Cash').reduce((n,s)=>n+s.value,0);
 const overloaded=visible.filter(m=>count(m)>capacity),outside=rows.filter(s=>{const p=model.projects.find(p=>p.id===s.projectId)!,w=timeline(p,a);return s.month<w.salesStart||s.month>=w.salesStart+w.salesDuration}).reduce((n,s)=>n+s.units,0);
 const finish=(rs:typeof rows)=>rs.length?tr(modelMonthLabel(model.startDate,Math.max(...rs.map(s=>s.month)))):'—';
 const metrics=[[t('Потребность в финансировании','Funding requirement'),money(baseline.peak,false,model.currency),money(stress.peak,false,model.currency)],[t('Месяц максимального дефицита','Peak funding month'),baseline.peakMonth?tr(modelMonthLabel(model.startDate,baseline.peakMonth)):'—',stress.peakMonth?tr(modelMonthLabel(model.startDate,stress.peakMonth)):'—'],[t('Завершение продаж','Sales completion'),finish(baseRows),finish(stressedRows)],[t('Выручка','Revenue'),money(baseline.revenue,false,model.currency),money(stress.revenue,false,model.currency)],[t('Прибыль после общих затрат','Profit after company costs'),money(baseline.profit,false,model.currency),money(stress.profit,false,model.currency)],[t('Маржа','Margin'),percent(baseline.margin),percent(stress.margin)]];
 const invalid=model.projects.some(p=>p.units.some(u=>u.quantity!==u.tiers.reduce((n,t)=>n+t.units,0)||u.tiers.some(t=>(t.schedule?.mode||p.salesMode)==='MANUAL'&&t.units!==t.manual.reduce((n,v)=>n+v,0))));
 return <div className="stack portfolio-plan">
 <section className="card"><h2>{t('План продаж портфеля','Portfolio sales plan')}</h2><p>{t('Ориентиры задаёте вы: это допущения для проверки, а не рыночные нормативы.','These are your planning assumptions, not market benchmarks.')}</p><div className="form-grid"><Field label={t('Сделок в месяц · весь портфель','Deals per month · whole portfolio')} type="number" min={1} max={1000} step={1} value={capacity} onChange={setCapacity}/><Field label={t('Максимальная доля Full Cash · % юнитов','Maximum Full Cash share · % of units')} type="number" max={100} value={cashPercent} onChange={setCash}/><label className="field"><span>{t('Период сводки','Summary period')}</span><AppSelect value={year} onChange={e=>setYear(e.target.value)}><option value="all">{t('Весь срок','Whole model')}</option>{years.map(y=><option key={y}>{y}</option>)}</AppSelect></label></div>
 <div className="tabs"><button className={!preview?'active':''} onClick={()=>setPreview(false)}>{t('Текущий план','Current plan')}</button><button className={preview?'active':''} onClick={()=>setPreview(true)}>{t('Осторожный сценарий','Cautious scenario')}</button></div>
 <div className="notice">{t('Продажи','Sales')}: <b>{units}</b> · Full Cash: <b>{cashUnits} / {units} ({percent(units?cashUnits/units:0)})</b> · {t('Доля в стоимости договоров','Share of contract value')}: <b>{percent(value?cashValue/value:0)}</b></div>
 {overloaded.length>0&&<p className="warning">{t('Месяцев выше мощности','Months over capacity')}: {overloaded.length}. {t('Максимум сделок в месяц','Maximum monthly deals')}: {Math.max(...visible.map(countMonth=>count(countMonth)))} / {capacity}.</p>}
 {units>0&&cashUnits/units*100>cashPercent&&<p className="warning">{t('Доля Full Cash выше вашего ориентира.','Full Cash share exceeds your assumption.')}</p>}
 {outside>0&&<p className="warning">{t('За пределами исходных периодов продаж','Outside original sales windows')}: {outside} {t('юнитов','units')}.</p>}
 {invalid&&<p className="warning">{t('В исходном плане есть несоответствие количества юнитов. Сравнение использует только распределённые продажи; исправьте распределение перед сохранением сценария.','Source unit allocations do not match inventory. Comparison uses scheduled sales only; fix allocations before saving the scenario.')}</p>}
 <div className="table-scroll"><table className="data-table financial-table"><thead><tr><th>{t('Проект / показатель','Project / metric')}</th>{visible.map(m=><th key={m}>M{m}<br/>{tr(modelMonthLabel(model.startDate,m))}</th>)}<th>{t('Итого','Total')}</th></tr></thead><tbody>{model.projects.map(p=><tr key={p.id}><td><button className="btn" onClick={()=>setEditing(editing===p.id?null:p.id)}>{p.name} ↗</button></td>{visible.map(m=><td key={m}><button className="sales-cell-edit" aria-label={`${p.name} M${m}`} onClick={()=>setEditing(p.id)}>{count(m,p.id)}</button></td>)}<td>{selected.filter(s=>s.projectId===p.id).reduce((n,s)=>n+s.units,0)}</td></tr>)}
 <tr className="total"><td>{t('Всего продаж','Total sales')}</td>{visible.map(m=><td key={m} className={count(m)>capacity?'sales-overload':''}>{count(m)}{count(m)>capacity?' ⚠':''}</td>)}<td>{units}</td></tr><tr><td>Full Cash</td>{visible.map(m=><td key={m}>{cash(m)}</td>)}<td>{cashUnits}</td></tr><tr><td>{t('Доля Full Cash','Full Cash share')}</td>{visible.map(m=><td key={m} className={count(m)&&cash(m)/count(m)*100>cashPercent?'sales-overload':''}>{count(m)?percent(cash(m)/count(m)):'—'}</td>)}<td>{percent(units?cashUnits/units:0)}</td></tr></tbody></table></div>
 <p>{t('Нажмите на проект или ячейку, чтобы раскрыть редактор исходного плана ниже.','Click a project or cell to expand the source plan editor below.')}</p></section>
 {editing&&model.projects.find(p=>p.id===editing)&&<section className="card"><div className="row spread"><h2>{model.projects.find(p=>p.id===editing)!.name}</h2><button className="btn" onClick={()=>setEditing(null)}>{t('Закрыть','Close')}</button></div><ProjectEditor key={editing} project={model.projects.find(p=>p.id===editing)!} startDate={model.startDate} a={a} initial="Sales" onChange={p=>onChange({...model,projects:model.projects.map(x=>x.id===p.id?p:x)})}/></section>}
 <section className="card"><h2>{t('Проверка осторожного сценария','Cautious scenario check')}</h2><p>{t('Лимит сделок применяется ко всему сроку портфеля. Излишек переносится вперёд в порядке исходных дат. Full Cash ограничивается по всему портфелю, с округлением вниз до целых юнитов.','Capacity applies to the whole portfolio horizon. Excess deals move forward in original date order. Full Cash is capped across the portfolio, rounded down to whole units.')}</p><div className="form-grid"><Field label={t('Первый взнос новых рассрочек · %','New installment down payment · %')} type="number" max={100} value={down} onChange={setDown}/><Field label={t('Срок новых рассрочек · месяцев','New installment term · months')} type="number" min={1} max={120} step={1} value={term} onChange={setTerm}/><Field label={t('Изменение цены при переводе в рассрочку · %','Price change on installment conversion · %')} type="number" min={-99} max={200} value={priceChange} onChange={setPrice}/></div><p>{t('Настройки рассрочки применяются только к переведённым из Full Cash юнитам. Платежи могут продолжаться после передачи объекта; поправка срока выбранного сценария также действует. Существующие рассрочки сохраняют свои условия.','Installment settings apply only to converted Full Cash units. Payments may continue after handover; the active scenario term adjustment also applies. Existing installment terms are retained.')}</p>
 <table className="data-table"><thead><tr><th>{t('Показатель · весь срок','Metric · full horizon')}</th><th>{t('Текущий план','Current plan')}</th><th>{t('Осторожный сценарий','Cautious scenario')}</th></tr></thead><tbody>{metrics.map(row=><tr key={row[0]}>{row.map((v,i)=><td key={i}>{v}</td>)}</tr>)}</tbody></table>
 <p className="warning">{t('Сроки строительства, зарплат и фиксированных расходов не продлеваются автоматически. Затраты, привязанные к периоду продаж, пересчитываются при его удлинении. Если продажи затянутся, проверьте периоды работы компании отдельно.','Construction, payroll and fixed expense periods do not extend automatically. Costs tied to the sales period recalculate when it extends. Review company operating periods if sales take longer.')}</p>
 <button className="btn dark" disabled={invalid||!baseRows.length} onClick={()=>{const copy=copyModel(projected);copy.name=`${model.name} · ${t('Осторожный план','Cautious plan')}`;useModels.getState().importModel(copy);notify(t('Сценарий сохранён отдельной моделью на устройстве. Для облака сохраните его в настройках.','Scenario saved as a separate local model. Save to cloud in Settings.'))}}>{t('Сохранить сценарий отдельной моделью','Save scenario as a separate model')}</button></section>
 </div>;
}
