import {chromium} from 'playwright';
import assert from 'node:assert/strict';
const browser=await chromium.launch({headless:true});
const page=await browser.newPage({viewport:{width:1512,height:1100},deviceScaleFactor:1});
const errors=[];page.on('pageerror',e=>errors.push(e.message));
await page.goto('http://127.0.0.1:3100',{waitUntil:'networkidle'});
await page.getByText('Your portfolio, in perspective.').waitFor();
assert.match(await page.locator('body').innerText(),/\$9M/);
await page.screenshot({path:'artifacts/dashboard.png',fullPage:true});
await page.getByRole('button',{name:'Employees',exact:true}).click();
const management=page.locator('.department-card').filter({has:page.getByRole('heading',{name:'Management',exact:true})});
await management.getByRole('button',{name:'Work period'}).click();
await management.getByLabel('Working duration · months').fill('14');
assert.match(await management.innerText(),/\$70,000/);
await page.getByRole('button',{name:'Department timeline',exact:true}).click();
assert.match(await page.locator('body').innerText(),/Departments · salary periods/);
await page.getByRole('button',{name:'Employees',exact:true}).click();
await management.getByRole('button',{name:'Work period'}).click();
assert.equal(await management.getByLabel('Working duration · months').inputValue(),'14');
await management.getByLabel('Working duration · months').fill('12');
await page.getByRole('button',{name:/^Projects/}).click();
await page.getByRole('button',{name:'Edit project'}).first().click();
await page.getByRole('button',{name:'Timeline',exact:true}).last().click();
const duration=page.getByLabel('PBG duration · months');await duration.fill('6');
assert.match(await page.getByRole('dialog').innerText(),/Sales M7/);
await duration.fill('4');await page.getByRole('button',{name:'Close',exact:true}).click();
await page.getByRole('button',{name:'Timeline',exact:true}).first().click();
const bar=page.locator('.gantt-bar').filter({hasText:'4 mo'}).first();const box=await bar.boundingBox();await page.mouse.move(box.x+box.width/2,box.y+12);await page.mouse.down();await page.mouse.move(box.x+box.width/2+60,box.y+12,{steps:8});await page.mouse.up();
await page.getByRole('button',{name:'Cash Flow',exact:true}).click();await page.getByText('TOTAL INFLOW',{exact:true}).waitFor();
await page.getByRole('button',{name:'Scenarios',exact:true}).click();await page.getByRole('button',{name:'Duplicate active scenario'}).click();assert.match(await page.locator('body').innerText(),/Base copy/);
await page.getByRole('button',{name:'Reports',exact:true}).click();const downloadEvent=page.waitForEvent('download');await page.getByRole('button',{name:'Export Excel',exact:true}).click();const dl=await downloadEvent;await dl.saveAs('artifacts/model.xlsx');
await page.getByRole('button',{name:'Settings',exact:true}).click();await page.getByLabel('Version name').fill('QA snapshot');await page.getByRole('button',{name:'Save version',exact:true}).click();await page.getByText('QA snapshot',{exact:true}).waitFor();
await page.reload({waitUntil:'networkidle'});await page.getByRole('button',{name:'Settings',exact:true}).click();await page.getByText('QA snapshot',{exact:true}).waitFor();
await page.setViewportSize({width:390,height:844});await page.getByRole('button',{name:'Overview',exact:true}).click();await page.screenshot({path:'artifacts/mobile.png',fullPage:true});const overflow=await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth);assert.equal(overflow,false,'Mobile page must not overflow');
console.log(JSON.stringify({errors,checks:12}));await browser.close();assert.equal(errors.length,0);
