'use client';
import {AppSelect} from '@/components/ui/app-select';
import {tr,useLanguage} from '@/lib/i18n';
import {useState} from 'react';
import {BarChart,Bar,XAxis,YAxis,Tooltip,ResponsiveContainer,CartesianGrid} from 'recharts';
import {ArrowUpRight} from 'lucide-react';
import {Month} from '@/types/model';
import {annualSales,modelMonthDate} from '@/lib/model-calendar';
export function AnnualSales({months,startDate,onOpen}:{months:Month[];startDate:string;onOpen:()=>void}){useLanguage();const years=annualSales(months,startDate),[selected,setSelected]=useState<number|null>(null);const active=years.find(y=>y.year===selected)||years.find(y=>y.year===2027)||years[0];if(!active)return null;const chart=Array.from({length:12},(_,i)=>({label:new Date(Date.UTC(active.year,i,1)).toLocaleDateString('en-US',{month:'short',timeZone:'UTC'}),units:active.months.find(m=>modelMonthDate(startDate,m.month).getUTCMonth()===i)?.units||0}));return <section className="card annual-sales"><div className="card-heading"><div><h2>{tr("Monthly sales")}</h2><p>{tr("Units contracted across the portfolio")}</p></div><div className="row"><AppSelect aria-label={tr("Sales calendar year")} value={active.year} onChange={e=>setSelected(+e.target.value)}>{years.map(y=><option key={y.year} value={y.year}>{y.year}</option>)}</AppSelect><button className="icon-btn" aria-label={tr("Open sales")} onClick={onOpen}><ArrowUpRight size={18}/></button></div></div><div className="annual-sales-total" aria-live="polite"><strong>{active.units.toLocaleString('en-US')}</strong><div><b>{tr("Total units sold in ")}{active.year}</b><small>{tr("January–December ")}{active.year}</small></div></div><ResponsiveContainer width="100%" height={220}><BarChart data={chart}><CartesianGrid vertical={false} stroke="#eceeea"/><XAxis dataKey="label" tickFormatter={tr} tick={{fontSize:12}} minTickGap={16} axisLine={false} tickLine={false}/><YAxis allowDecimals={false} width={28} tick={{fontSize:12}} axisLine={false} tickLine={false}/><Tooltip labelFormatter={v=>`${v} ${active.year}`}/><Bar isAnimationActive={false} dataKey="units" name="Units sold" fill="#799785" radius={[4,4,0,0]}/></BarChart></ResponsiveContainer></section>}
