'use client';
import {salesMilestone} from '@/lib/sales-milestone';
import {amountTone,financialColors} from '@/lib/financial-colors';
import {tr,useLanguage} from '@/lib/i18n';
import {useId} from 'react';
import {AnnualSales} from './annual-sales';
import {AreaChart,Area,XAxis,YAxis,Tooltip,ResponsiveContainer,CartesianGrid,ReferenceLine,BarChart,Bar,PieChart,Pie,Cell} from 'recharts';
import {ArrowUpRight,ArrowRight,SlidersHorizontal,RotateCcw,Plus} from 'lucide-react';
import {FinancialModel,Adjustments,Result} from '@/types/model';
import {calculatePortfolioCashFlow,timeline} from '@/lib/financial-engine';
import {money as formatMoney,number,percent} from '@/lib/format';
import {Slider} from '@/components/ui/controls';
type R=ReturnType<typeof calculatePortfolioCashFlow>;
export function CashChart({r,monthly=false,currency='USD',scope='portfolio'}:{r:Result & {projects?:Result[]};monthly?:boolean;currency?:string;scope?:'project'|'portfolio'}){useLanguage();const milestone=salesMilestone(r.months,r.units);const gradient=useId().replace(/:/g,''),lo=Math.min(0,...r.months.map(m=>m.cumulative)),hi=Math.max(0,...r.months.map(m=>m.cumulative)),split=hi===lo?0:hi/(hi-lo);const money=(n:number,c=false)=>formatMoney(n,c,currency);return <><ResponsiveContainer width="100%" height={270}>{monthly?<BarChart data={r.months}><CartesianGrid vertical={false} stroke="#eceeea"/><XAxis dataKey="label" tickFormatter={tr} tick={{fontSize:12,fill:'#7c827e'}} axisLine={false} tickLine={false} minTickGap={32}/><YAxis tickFormatter={v=>money(v,true)} tick={{fontSize:12,fill:'#7c827e'}} axisLine={false} tickLine={false} width={60}/><Tooltip formatter={v=>money(Number(v))}/><ReferenceLine y={0} stroke="#c6ccc6"/><Bar isAnimationActive={false} dataKey="net" name="Net cash flow" fill="#3b6b58" radius={[3,3,0,0]}>{r.months.map(m=><Cell key={m.month} fill={m.net<0?financialColors.negative:financialColors.positive}/>)}</Bar></BarChart>:<AreaChart data={r.months} margin={{top:30,right:16,bottom:0,left:0}}><defs><linearGradient id={gradient} x1="0" y1="0" x2="0" y2="1"><stop offset={`${split*100}%`} stopColor={financialColors.positive}/><stop offset={`${split*100}%`} stopColor={financialColors.negative}/></linearGradient></defs><CartesianGrid vertical={false} stroke="#eceeea"/><XAxis dataKey="label" tickFormatter={tr} tick={{fontSize:12,fill:'#7c827e'}} axisLine={false} tickLine={false} minTickGap={32}/><YAxis domain={[lo,hi||1]} tickFormatter={v=>money(v,true)} tick={{fontSize:12,fill:'#7c827e'}} axisLine={false} tickLine={false} width={64}/><Tooltip formatter={v=>money(Number(v))} contentStyle={{borderRadius:12,border:'1px solid #e6e6e3'}}/><ReferenceLine y={0} stroke="#b7c4b9" strokeDasharray="4 4"/>{milestone&&<ReferenceLine x={milestone.label} stroke="#2d7057" strokeWidth={2} strokeDasharray="6 4" label={{value:tr('≥70% sold · positive cash flow'),position:'top',fill:'#2d7057',fontSize:12}}/>}<Area isAnimationActive={false} type="monotone" dataKey="cumulative" name="Cumulative cash flow" stroke={`url(#${gradient})`} strokeWidth={2.5} fill={`url(#${gradient})`} fillOpacity={.13}/></AreaChart>}</ResponsiveContainer>{!monthly&&<div className="sales-milestone-note" role="status">{milestone?<><strong>Продано ≥70% · накопленный поток положительный</strong><span>{tr(milestone.label)} · M{milestone.month} · {milestone.sold} / {r.units} {tr('units')} ({percent(milestone.share)})</span><small>Первый месяц, когда продано не менее 70% юнитов {scope==='project'?'проекта':'портфеля'} и накопленный денежный поток положительный.</small></>:<span>Условие пока не достигнуто: необходимо продать ≥70% юнитов и получить положительный накопленный поток.</span>}</div>}</>}
export function Dashboard({model,r,a,adjust,navigate,edit,add,readOnly=false}:{readOnly?:boolean;model:FinancialModel;r:R;a:Adjustments;adjust:(v:Partial<Adjustments>)=>void;navigate:(view:string)=>void;edit:(id:string)=>void;add:()=>void}){useLanguage();const money=(n:number,c=false)=>formatMoney(n,c,model.currency);const colors=['#ad4b3d','#bf7562','#c29a62','#d3b694','#976354','#e3cebd'];const costData=Object.entries(r.costs).sort((a,b)=>b[1]-a[1]);return <>
<div className="section-intro"><div><span className="eyebrow">{tr("PORTFOLIO OVERVIEW")}</span><h1>{tr("Your portfolio, in perspective.")}</h1><p>{model.projects.length}{tr(" projects ")}<span>·</span> {number(r.units)}{tr(" units ")}<span>·</span> {number(r.gla)}{tr(" m² GLA ")}<span>·</span> {r.duration}{tr(" month lifecycle")}</p></div><button className="btn" onClick={()=>navigate('Timeline')}>{tr("View timeline ")}<ArrowUpRight size={16}/></button></div>
<div className="kpi-grid">{[{label:'Total revenue',value:money(r.revenue,true),sub:'Contracted development sales',view:'Sales'},{label:'Development profit',value:money(r.profit,true),sub:`${percent(r.margin)} profit margin`,view:'P&L'},{label:'Development cost',value:money(r.cost,true),sub:`${money(r.gla?r.cost/r.gla:0)} per m²`,view:'Costs'},{label:'Peak funding need',value:money(r.peak,true),sub:r.peakMonth?`${r.months[r.peakMonth-1]?.label} · Month ${r.peakMonth}`:'No funding gap',view:'Cash Flow'}].map((k,i)=><button key={tr(k.label)} className={`kpi ${i===0?'primary':''}`} onClick={()=>navigate(k.view)}><div>{tr(k.label)}<ArrowUpRight size={16}/></div><strong className={amountTone([r.revenue,r.profit,r.cost,r.peak][i],i===2?'expense':i===3?'funding':'balance')}>{k.value}</strong><small>{i===1&&<span className="status-dot"/>}{tr(k.sub)}</small></button>)}</div>
<div className="financial-color-legend"><span className="amount-positive">● {tr("Income / positive result")}</span><span className="amount-negative">● {tr("Expenses / losses")}</span><span className="amount-funding">● {tr("Funding requirement")}</span></div><div className="dashboard-grid"><section className="card cash-card"><div className="card-heading"><div><h2>{tr("Cumulative cash flow")}</h2><p>{tr("Capital deployed. Value created.")}</p></div><span className="legend"><i/> {tr(model.scenarios.find(s=>s.id===model.activeScenario)?.name||'')}{tr(" scenario")}</span></div><CashChart r={r} currency={model.currency}/><footer className="chart-footer"><span>{tr("Funding trough ")}<b className={amountTone(-r.peak)}>{money(-r.peak,true)}</b></span><span>{tr("Closing cash balance ")}<b className={amountTone(r.months.at(-1)?.cumulative||0)}>{money(r.months.at(-1)?.cumulative||0,true)}</b></span></footer></section>
<section className="card revenue-card"><div className="card-heading"><div><h2>{tr("Revenue by project")}</h2><p>{money(r.revenue,true)}{tr(" total development sales")}</p></div></div><div className="revenue-bars">{model.projects.map((p,i)=><button className="revenue-row" key={p.id} onClick={()=>edit(p.id)}><div><span>{p.name}</span><b>{money(r.projects[i].revenue,true)}</b></div><div className="track"><i style={{width:`${r.revenue?r.projects[i].revenue/r.revenue*100:0}%`,background:p.color}}/></div><small>{r.projects[i].units}{tr(" units · ")}{percent(r.revenue?r.projects[i].revenue/r.revenue:0)}{tr(" of portfolio")}</small></button>)}</div><div className="mini-stats"><div><small>{tr("Average selling price")}</small><b>{money(r.units?r.revenue/r.units:0)}</b></div><div><small>{tr("Revenue / m²")}</small><b>{money(r.gla?r.revenue/r.gla:0)}</b></div></div></section></div>
<div className="card timeline-summary"><div className="card-heading"><div><h2>{tr("Development roadmap")}</h2><p>{tr("From land control to handover")}</p></div><button className="text-btn" onClick={()=>navigate('Timeline')}>{tr("Open timeline ")}<ArrowRight size={15}/></button></div><div className="roadmap-axis"><span>{tr("PROJECT")}</span>{Array.from({length:7},(_,i)=>1+Math.round(i*(Math.max(1,r.duration)-1)/6)).map((n,i)=><span key={i}>{tr("M")}{n}</span>)}</div>{model.projects.map(p=>{const t=timeline(p,a);return <div className="roadmap-row" key={p.id}><button onClick={()=>edit(p.id)}><i style={{background:p.color}}/>{p.name}</button><div className="roadmap-track"><span className="permit-bar" style={{left:`${(t.pbgStart-1)/Math.max(1,r.duration)*100}%`,width:`${t.pbgDuration/Math.max(1,r.duration)*100}%`}}>{tr("PBG")}</span><span className="build-bar" style={{left:`${(t.constructionStart-1)/Math.max(1,r.duration)*100}%`,width:`${t.constructionDuration/Math.max(1,r.duration)*100}%`,background:p.color}}>{tr("Construction")}</span></div></div>})}<div className="timeline-legend"><span><i className="permit-dot"/>{tr(" PBG / Permits")}</span><span><i/>{tr(" Construction")}</span></div></div>
<div className="dashboard-grid lower"><AnnualSales key={model.id} months={r.months} startDate={model.startDate} onOpen={()=>navigate('Sales')}/><section className="card"><div className="card-heading"><div><h2>{tr("Cost composition")}</h2><p>{tr("Percentages of total revenue")}</p></div></div><div className="cost-composition"><ResponsiveContainer width="45%" height={200}><PieChart><Pie isAnimationActive={false} data={costData.map(([name,value])=>({name,value}))} innerRadius="58%" outerRadius="82%" dataKey="value" paddingAngle={2}>{costData.map((_,i)=><Cell key={i} fill={colors[i%colors.length]}/>)}</Pie><Tooltip formatter={v=>`${money(Number(v))} · ${r.revenue?percent(Number(v)/r.revenue):'—'} ${tr('of revenue')}`}/></PieChart></ResponsiveContainer><div>{costData.slice(0,5).map(([k,v],i)=><div className="cost-legend" key={k}><i style={{background:colors[i]}}/><span>{tr(k)}</span><b>{r.revenue?percent(v/r.revenue):'—'}</b></div>)}</div></div></section></div>
{!readOnly&&<section className="card what-if"><div className="card-heading"><div><h2><SlidersHorizontal size={17}/>{tr(" What if?")}</h2><p>{tr("Explore the impact. Every change updates your active scenario.")}</p></div><button className="text-btn" onClick={()=>adjust({price:0,construction:0,speed:0,pbgDelay:0,land:0})}><RotateCcw size={14}/>{tr(" Reset")}</button></div><div className="what-if-grid"><Slider label={tr("Sales price")} value={a.price} min={-20} max={30} onChange={price=>adjust({price})}/><Slider label={tr("Construction cost")} value={a.construction} min={-20} max={30} onChange={construction=>adjust({construction})}/><Slider label={tr("Sales speed")} value={a.speed} min={-50} max={50} onChange={speed=>adjust({speed})}/><Slider label={tr("PBG delay")} value={a.pbgDelay} min={0} max={12} suffix=" mo" onChange={pbgDelay=>adjust({pbgDelay})}/><Slider label={tr("Land cost")} value={a.land} min={-20} max={30} onChange={land=>adjust({land})}/></div></section>}
<div className="section-title"><h2>{tr("Your projects ")}<span>{model.projects.length}</span></h2>{!readOnly&&<button className="btn" onClick={add}><Plus size={15}/>{tr(" Add project")}</button>}</div><div className="project-cards">{model.projects.map((p,i)=>{const pr=r.projects[i],t=timeline(p,a);return <button className="card project-card" key={p.id} onClick={()=>edit(p.id)}><div className="project-top"><span className="project-symbol" style={{background:p.color}}>{String(i+1).padStart(2,'0')}</span><span className="badge">{tr(p.status)}</span><ArrowUpRight size={17}/></div><h3>{p.name}</h3><p>{p.location}</p><div className="project-details"><span>{pr.units}{tr(" units")}</span><span>{number(pr.gla)}{tr(" m²")}</span><span className={amountTone(pr.margin)}>{percent(pr.margin)}{tr(" margin")}</span></div><div className="project-finance"><div><small>{tr("Revenue")}</small><strong className={amountTone(pr.revenue)}>{money(pr.revenue,true)}</strong></div><div><small>{tr("Profit")}</small><strong className={amountTone(pr.profit)}>{money(pr.profit,true)}</strong></div></div><footer>{tr("PBG M")}{t.pbgStart}–{t.pbgEnd} <span>{tr("Construction M")}{t.constructionStart}–{t.completion}</span></footer></button>})}</div>
</>}
