'use client';
import {AppSelect} from '@/components/ui/app-select';
import {PortfolioPlan} from '@/features/sales/portfolio-plan';
import {appPath,staticHosting} from '@/lib/app-path';
import {amountTone,financialColors} from '@/lib/financial-colors';
import {tr,useLanguage} from '@/lib/i18n';
import {copyModel} from '@/lib/copy-model';
import {copyProjectStaff,removeProjectStaff} from '@/lib/workforce';
import {useState} from 'react';
import {Plus,Copy,Trash2,ArrowUp,ArrowDown,ArrowUpRight,Download,History,Save,Building2,FileText} from 'lucide-react';
import {FinancialModel,Adjustments,Project,neutral} from '@/types/model';
import {calculatePortfolioCashFlow,calculateProjectCashFlow} from '@/lib/financial-engine';
import {useModels} from '@/store/model-store';
import {ProjectEditor} from '@/features/projects/project-editor';
import {TimelineView} from '@/features/timeline/timeline';
import {CashFlowView} from '@/features/cashflow/cashflow';
import {EmployeesView} from '@/features/employees/employees';
import {CorporateEditor} from '@/features/corporate/corporate';
import {CloudSettings} from './cloud';
import {Field,Slider,Select} from '@/components/ui/controls';
import {money as formatMoney,percent,number} from '@/lib/format';
import {supabase} from '@/lib/supabase';
import {id} from '@/lib/demo';
import {exportExcel,downloadBlob} from '@/lib/export/excel';
export function WorkspaceView({view,model,a,onChange,navigate,edit,add,notify}:{view:string;model:FinancialModel;a:Adjustments;onChange:(m:FinancialModel)=>void;navigate:(s:string)=>void;edit:(id:string,tab?:string)=>void;add:()=>void;notify:(s:string)=>void}){useLanguage();const money=(n:number,c=false)=>formatMoney(n,c,model.currency);const store=useModels();const [pid,setPid]=useState(model.projects[0]?.id||'');const [costTab,setCostTab]=useState('Project costs');const [versionName,setVersionName]=useState('Investor v1');const [busy,setBusy]=useState(false);const p=model.projects.find(p=>p.id===pid)||model.projects[0];const update=(q:Project)=>onChange({...model,projects:model.projects.map(x=>x.id===q.id?q:x)});const r=calculatePortfolioCashFlow(model,a);const duplicate=(p:Project)=>{const q=structuredClone(p);q.id=id();q.name+=' · Copy';q.units=q.units.map(u=>({...u,id:id(),tiers:u.tiers.map(t=>({...t,id:id()}))}));q.costs=q.costs.map(c=>({...c,id:id()}));q.payroll=q.payroll.map(e=>({...e,id:id()}));onChange(copyProjectStaff({...model,projects:[...model.projects,q]},p.id,q.id,id));notify('Project duplicated.')};const remove=(p:Project)=>{if(confirm(`Delete ${p.name}? Company employees will remain. Save a version first if you need to restore it.`))onChange({...removeProjectStaff(model,p.id),projects:model.projects.filter(x=>x.id!==p.id)})};const exportFile=async(pdf=false)=>{setBusy(true);try{if(pdf&&staticHosting){window.open(appPath('/report/'),'_blank');notify('Use Print → Save as PDF.');return}if(pdf){const response=await fetch('/api/report',{method:'POST',headers:{'Content-Type':'application/json',...(supabase()?{Authorization:'Bearer '+(await supabase()!.auth.getSession()).data.session?.access_token}:{})},body:JSON.stringify(model)});if(!response.ok)throw Error((await response.json()).error);downloadBlob(await response.blob(),`${model.name}.pdf`)}else await exportExcel(model);notify(`${pdf?'PDF':'Excel'} report exported.`)}catch(e){notify(e instanceof Error?e.message:'Export failed')}finally{setBusy(false)}};
if(view==='Models')return <><a className="btn" style={{marginBottom:20}} href={appPath('/invited/')}>{tr('Models shared with me')}</a><div className="view-title"><div><h1>{tr("Financial models")}</h1><p>{tr("Your development investment workspace.")}</p></div><button className="btn dark" onClick={()=>{store.newModel();navigate('Overview')}}><Plus size={15}/>{tr(" New Financial Model")}</button></div><div className="project-cards">{store.models.map(m=>{const v=calculatePortfolioCashFlow(m,m.scenarios.find(s=>s.id===m.activeScenario)?.adjustments||neutral);return <div className="model-card-wrapper" key={m.id}><button className="card project-card model-open" onClick={()=>{store.selectModel(m.id);navigate('Overview')}}><Building2 size={25}/><h3 style={{marginTop:20}}>{m.name}</h3><p>{new Date(m.created).toLocaleDateString()} · {m.projects.length}{tr(" projects")}</p><div className="project-finance"><div><small>{tr("Revenue")}</small><strong>{money(v.revenue,true)}</strong></div><div><small>{tr("Profit")}</small><strong className={amountTone(v.profit)}>{money(v.profit,true)}</strong></div></div><p>{tr("Cost ")}{money(v.cost,true)}{tr(" · Margin ")}{percent(v.margin)}</p><p>{tr("Peak funding ")}{money(v.peak,true)}</p></button><button className="btn model-copy" aria-label={`${tr('Create copy')}: ${m.name}`} onClick={()=>{const copy=copyModel(m);copy.name=`${m.name} · ${tr('Copy')}`;store.importModel(copy);navigate('Overview');notify(tr('Copy created on this device. Save it to cloud in Settings to use it on other devices.'))}}><Copy size={16}/>{tr('Create copy')}</button><button className="delete-btn model-delete" disabled={store.models.length<=1} aria-label={`${tr('Remove model')}: ${m.name}`} title={tr(store.models.length<=1?'Keep at least one model':'Remove model')} onClick={()=>{if(confirm(`${tr('Remove this model from this device? A recoverable copy stays in Trash. The cloud copy is kept.')}\n\n${m.name}`)){store.deleteModel(m.id);notify(tr('Model moved to Trash.'))}}}><Trash2 size={18}/></button></div>})}</div>{store.deletedModels.length>0&&<details className="card" style={{marginTop:24}}><summary>{tr('Trash')} · {store.deletedModels.length}</summary><p>{tr('Trash is stored on this device. Cloud loading will not restore these models automatically.')}</p>{store.deletedModels.map(m=><div className="row spread" key={m.id} style={{marginTop:12}}><span>{m.name}</span><button className="btn" onClick={()=>{store.restoreDeletedModel(m.id);notify(tr('Model restored.'))}}>{tr('Restore')}</button></div>)}</details>}</>;
if(view==='Employees'||view==='Payroll')return <EmployeesView model={model} a={a} onChange={onChange} navigate={navigate}/>;
if(view==='Timeline')return <TimelineView model={model} a={a} onChange={onChange} edit={pid=>edit(pid,'Timeline')}/>;
if(view==='Cash Flow'||view==='P&L')return <CashFlowView model={model} a={a} pnl={view==='P&L'}/>;
if(view==='Projects')return <><div className="view-title"><div><h1>{tr("Development projects")}</h1><p>{model.projects.length}{tr(" projects · ")}{r.units}{tr(" units · ")}{number(r.gla)}{tr(" m²")}</p></div><button className="btn dark" onClick={add}><Plus size={15}/>{tr(" Add project")}</button></div>{!p?<div className="card empty"><Building2 size={35}/><h2>{tr("Your first development starts here")}</h2><p>{tr("Add land, units and a timeline to build your financial model.")}</p><button className="btn dark" onClick={add}>{tr("Add project")}</button></div>:<div className="stack">{model.projects.map((p,i)=>{const v=r.projects[i];return <section className="card" key={p.id}><div className="row spread"><div><span className="badge">{tr(p.status)}</span><h3 style={{marginTop:8}}>{p.name}</h3><p style={{color:'var(--muted)',fontSize:12}}>{p.location}</p></div><div className="row"><button className="icon-btn" aria-label={`Move ${p.name} up`} disabled={i===0} onClick={()=>{const ps=[...model.projects];[ps[i],ps[i-1]]=[ps[i-1],ps[i]];onChange({...model,projects:ps})}}><ArrowUp size={16}/></button><button className="icon-btn" aria-label={`Move ${p.name} down`} disabled={i===model.projects.length-1} onClick={()=>{const ps=[...model.projects];[ps[i],ps[i+1]]=[ps[i+1],ps[i]];onChange({...model,projects:ps})}}><ArrowDown size={16}/></button><button className="icon-btn" aria-label={`Duplicate ${p.name}`} onClick={()=>duplicate(p)}><Copy size={16}/></button><button className="delete-btn" aria-label={`Delete ${p.name}`} onClick={()=>remove(p)}><Trash2 size={16}/></button><button className="btn" onClick={()=>edit(p.id)}>{tr("Edit project ")}<ArrowUpRight size={14}/></button></div></div><div className="project-details"><span>{v.units}{tr(" units")}</span><span>{number(v.gla)}{tr(" m²")}</span><span>{tr("Revenue ")}{money(v.revenue,true)}</span><span>{tr("Profit ")}{money(v.profit,true)}</span><span>{percent(v.margin)}{tr(" margin")}</span></div></section>})}</div>}</>;
if(view==='Sales')return <PortfolioPlan key={model.id} model={model} a={a} onChange={onChange} notify={notify}/>;
if(['Land','Construction','Costs'].includes(view)){const tab=view==='Costs'?'Costs':view;return <><div className="view-title"><div><h1>{view==='Sales'?'Sales & buyer payments':view==='Costs'?'Development costs':view}</h1><p>{tr("Edit assumptions to update your financial model instantly.")}</p></div><AppSelect aria-label={tr("Select project")} value={p?.id||''} onChange={e=>setPid(e.target.value)}>{model.projects.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</AppSelect></div>{(view==='Costs')&&<div className="tabs">{['Project costs','Company operating costs'].map(t=><button key={t} className={t===costTab?'active':''} onClick={()=>setCostTab(t)}>{tr(t)}</button>)}</div>}{(view==='Costs')&&costTab==='Company operating costs'?<CorporateEditor model={model} onChange={onChange}/>:p?<section className="card"><ProjectEditor startDate={model.startDate} key={view+p.id} project={p} onChange={update} initial={tab} a={a}/></section>:<div className="card empty"><p>{tr("Add a project to begin.")}</p><button className="btn dark" onClick={add}>{tr("Add project")}</button></div>}</>}
if(view==='Scenarios')return <><div className="view-title"><div><h1>{tr("Scenario studio")}</h1><p>{tr("Compare the economics before committing capital.")}</p></div><button className="btn dark" onClick={()=>{const s=model.scenarios.find(s=>s.id===model.activeScenario)!;const sid=id();onChange({...model,activeScenario:sid,scenarios:[...model.scenarios,{...structuredClone(s),id:sid,name:s.name+' copy'}]})}}><Copy size={15}/>{tr(" Duplicate active scenario")}</button></div><section className="card" style={{marginBottom:20}}><div className="table-scroll"><table className="data-table"><thead><tr><th>{tr("Scenario")}</th><th>{tr("Revenue")}</th><th>{tr("Cost")}</th><th>{tr("Profit")}</th><th>{tr("Margin")}</th><th>{tr("Peak funding")}</th><th>{tr("Duration")}</th><th/></tr></thead><tbody>{model.scenarios.map(s=>{const v=calculatePortfolioCashFlow(model,s.adjustments);return <tr key={s.id} className={model.activeScenario===s.id?'total':''}><td><button onClick={()=>onChange({...model,activeScenario:s.id})}>{s.name} {tr(model.activeScenario===s.id?'✓':'')}</button></td><td className={amountTone(v.revenue,'balance')}>{money(v.revenue,true)}</td><td className={amountTone(v.cost,'expense')}>{money(v.cost,true)}</td><td className={amountTone(v.profit,'balance')}>{money(v.profit,true)}</td><td className={amountTone(v.margin)}>{percent(v.margin)}</td><td className={amountTone(v.peak,'funding')}>{money(v.peak,true)}</td><td>{v.duration}{tr(" mo")}</td><td><button disabled={model.scenarios.length===1} className="delete-btn" aria-label={`Delete ${s.name} scenario`} onClick={()=>{const list=model.scenarios.filter(x=>x.id!==s.id);onChange({...model,scenarios:list,activeScenario:model.activeScenario===s.id?list[0].id:model.activeScenario})}}><Trash2 size={14}/></button></td></tr>})}</tbody></table></div></section><section className="card"><Field label={tr("Active scenario name")} value={model.scenarios.find(s=>s.id===model.activeScenario)?.name||''} onChange={name=>onChange({...model,scenarios:model.scenarios.map(s=>s.id===model.activeScenario?{...s,name}:s)})}/><div className="form-grid" style={{marginTop:24}}>{Object.entries(a).map(([k,v])=><Field key={k} label={k.replace(/([A-Z])/g,' $1')} value={v} type="number" min={k==='pbgDelay'?0:k==='constructionDuration'?-17:k==='paymentTerm'?-17:-90} max={120} onChange={value=>onChange({...model,scenarios:model.scenarios.map(s=>s.id===model.activeScenario?{...s,adjustments:{...s.adjustments,[k]:value}}:s)})}/>)}</div></section></>;
if(view==='Reports')return <><div className="view-title"><div><h1>{tr("Investment reports")}</h1><p>{tr("Your model, ready for the investment conversation.")}</p></div></div><div className="settings-grid"><section className="card"><FileText size={27}/><h3 style={{marginTop:16}}>{tr("Excel financial model")}</h3><p className="report-description">{tr("14 structured worksheets. Assumptions, project schedules, buyer collections, monthly cash flow and P&L, with formulas and investment model formatting.")}</p><button className="btn dark" disabled={busy} onClick={()=>exportFile()}><Download size={15}/>{tr(busy?'Preparing…':'Export Excel')}</button></section><section className="card"><FilesIcon/><h3 style={{marginTop:16}}>{tr("Investment report · PDF")}</h3><p className="report-description">{tr("A dedicated report with executive summary, project economics, sales, land payments, capital requirement and scenario comparison.")}</p><div className="row"><button className="btn dark" disabled={busy} onClick={()=>exportFile(true)}><Download size={15}/>{tr(busy?'Preparing…':'Export PDF')}</button><a className="btn" href={appPath('/report')} target="_blank">{tr("Preview report")}</a></div></section></div></>;
if(view==='Settings')return <><div className="view-title"><div><h1>{tr("Model settings")}</h1><p>{tr("Model identity, saved versions and cloud workspace.")}</p></div></div><div className="stack"><section className="card"><div className="form-grid"><Field label={tr("Model name")} value={model.name} onChange={name=>onChange({...model,name})}/><Field label={tr("Model start date")} type="date" value={model.startDate} onChange={startDate=>{if(startDate)onChange({...model,startDate})}}/><Select label={tr("Reporting currency · no FX conversion")} value={model.currency} options={['USD','IDR','EUR','GBP','AUD','SGD']} onChange={currency=>onChange({...model,currency,projects:model.projects.map(p=>({...p,currency}))})}/></div></section><section className="card"><div className="card-heading"><h2><History size={17}/>{tr(" Version history")}</h2><button className="btn" onClick={async()=>{const sb=supabase();if(!sb){notify('Connect Supabase to load cloud versions.');return}const {data,error}=await sb.from('model_versions').select('id,name,data,created_at').eq('model_id',model.id).order('created_at',{ascending:false});if(error){notify(error.message);return}store.mergeVersions((data||[]).map(v=>({id:v.id,name:v.name,model:v.data,date:v.created_at})));notify('Cloud versions loaded.')}}>{tr("Load cloud versions")}</button></div><div className="row"><input aria-label={tr("Version name")} value={versionName} onChange={e=>setVersionName(e.target.value)}/><button className="btn dark" onClick={()=>{store.saveVersion(versionName||'Untitled version');notify('Version saved.')}}><Save size={14}/>{tr(" Save version")}</button></div>{store.versions.filter(v=>v.model.id===model.id).map(v=><div className="version-row" key={v.id}><div><b>{v.name}</b><small>{new Date(v.date).toLocaleString()}</small></div><button className="btn" onClick={()=>{store.saveVersion('Before restore · '+new Date().toLocaleTimeString());store.restore(v.id);notify('Version restored. Previous state backed up.')}}>{tr("Restore")}</button></div>)}</section><CloudSettings notify={notify}/><section className="card"><h2>{tr("Portable model backup")}</h2><p className="report-description">{tr("Save a complete JSON backup to move your model between devices.")}</p><div className="row"><button className="btn" onClick={()=>downloadBlob(new Blob([JSON.stringify(model,null,2)],{type:'application/json'}),`${model.name}.json`)}>{tr("Download model backup")}</button></div></section></div></>;
return null}
function FilesIcon(){useLanguage();return <FileText size={27}/>}
