'use client';
import {AppSelect} from '@/components/ui/app-select';
import {useEffect,useMemo,useState} from 'react';
import {Building2,Plus,ArrowUpRight,Download,SlidersHorizontal,LayoutGrid,CalendarDays,ChartNoAxesCombined,Users,Save,Undo2,Trash2} from 'lucide-react';
import {useModels} from '@/store/model-store';
import {Project,FinancialModel,neutral} from '@/types/model';
import {calculateSalesPlan,timeline,projectWindow} from '@/lib/financial-engine';
import {defaultMarket,scopedResult,futurePrice,breakEvenPrice,matrix,npv} from '@/lib/sensitivity';
import {ProjectEditor} from '@/features/projects/project-editor';
import {WorkspaceView} from '@/features/models/workspace';
import {NumberInput} from '@/components/ui/number-input';
import {Dialog} from '@/components/ui/dialog';
import {createProject,id} from '@/lib/demo';
import {tr} from '@/lib/i18n';
import {downloadBlob} from '@/lib/export/excel';
import {InvestmentsView} from '@/features/investments/investments-view';
import {calculateFinancing} from '@/lib/investments';
import {removeProject} from '@/lib/remove-project';
import {EconomicsChart} from '@/features/projects/economics-chart';
import {ShareModel} from '@/features/models/share';
import {ModelImport} from '@/features/models/model-import';
import {CashChart} from '@/features/models/dashboard';
import {amountTone} from '@/lib/financial-colors';
import './v2.css';
const money=(v:number,currency:string)=>new Intl.NumberFormat('ru-RU',{style:'currency',currency,maximumFractionDigits:0}).format(v);
function Input({label,value,onChange,min=0,max=1e9,step=1}:{label:string;value:number;onChange:(n:number)=>void;min?:number;max?:number;step?:number}){return <label className="v-field"><span>{label}</span><NumberInput aria-label={label} value={value} min={min} max={max} step={step} onChange={e=>onChange(Math.max(min,Math.min(max,Number(e.target.value))))}/></label>}
export default function Home(){
 const s=useModels(),[ready,setReady]=useState(false),[scope,setScope]=useState('portfolio'),[view,setView]=useState('studio'),[edit,setEdit]=useState<{id:string;tab:string}|null>(null),[year,setYear]=useState(0),[metric,setMetric]=useState('margin'),[axis,setAxis]=useState<'speed'|'construction'>('speed'),[basis,setBasis]=useState<'operating'|'developer'>('operating'),[toast,setToast]=useState(''),[deleting,setDeleting]=useState<string|null>(null),[sharing,setSharing]=useState(false);
 useEffect(()=>setReady(true),[]);
 useEffect(()=>{setScope('portfolio');setEdit(null);setSharing(false);setYear(0);setView('studio')},[s.activeId]);
 const raw=s.models.find(m=>m.id===s.activeId)||s.models[0];
 const model=useMemo(()=>({...raw,projects:raw.projects.map(p=>({...p,market:p.market||defaultMarket()}))}),[raw]);
 const discount=model.analysis?.discount??15;
 const setDiscount=(discount:number)=>s.setModel({...model,analysis:{targetMargin:model.analysis?.targetMargin??30,...model.analysis,discount}});
 const a=model.scenarios.find(x=>x.id===model.activeScenario)?.adjustments||neutral;
 const selectScope=(next:string)=>{setScope(next);setView('studio');setYear(0);if(next!=='portfolio'&&(metric==='developerMargin'||metric==='fundingAfter'))setMetric('margin');if(a.projectId&&a.projectId!==next)s.setModel({...model,activeScenario:'base'})};
 useEffect(()=>{if(a.projectId)setScope(a.projectId)},[model.activeScenario,a.projectId]);
 const p=model.projects.find(p=>p.id===scope);
 const result=useMemo(()=>scopedResult(model,scope,a),[model,scope,a]);
 const projectPeriod=p?projectWindow(p,a):null;
 const firstMonth=Math.min(projectPeriod?.start??1,...result.months.filter(m=>m.inflow!==0||m.outflow!==0||m.units!==0).map(m=>m.month));
 const displayMonths=result.months.filter(m=>m.month>=firstMonth);
 const pageCount=Math.max(1,Math.ceil(displayMonths.length/12)),activeYear=year===-1?-1:Math.min(year,pageCount-1);
 const planMonths=activeYear===-1?displayMonths:displayMonths.slice(activeYear*12,activeYear*12+12);
 const chartResult={...result,months:displayMonths};
 const stabilityBasis=scope==='portfolio'?basis:'operating';
 const financing=useMemo(()=>calculateFinancing(model,a),[model,a]);
 const cells=useMemo(()=>matrix(model,scope,a,metric==='developerMargin'||metric==='fundingAfter',axis),[model,scope,a,metric,axis]);
 const boundary=useMemo(()=>breakEvenPrice(model,scope,a,stabilityBasis),[model,scope,a,stabilityBasis]);
 const economicProfit=stabilityBasis==='developer'?financing.developerProfit:result.profit,economicMargin=stabilityBasis==='developer'?financing.developerMargin:result.margin;
 const funding=stabilityBasis==='developer'?financing:result;
 const current=futurePrice(model,scope,a),fmt=(n:number)=>money(n,model.currency);
 const update=(q:Project)=>s.setModel({...model,projects:model.projects.map(x=>x.id===q.id?q:x)});
 const notice=(text:string)=>{setToast(text);setTimeout(()=>setToast(''),4000)};
 const add=()=>{const q={...createProject('Новый проект',model.projects.length),currency:model.currency,market:defaultMarket()};s.setModel({...model,projects:[...model.projects,q]});setScope(q.id);setView('studio');setEdit({id:q.id,tab:'Basic'})};
 const deleteTarget=model.projects.find(q=>q.id===deleting);
 const confirmDelete=()=>{if(!deleteTarget)return;s.saveVersion('До удаления · '+deleteTarget.name);s.setModel(removeProject(model,deleteTarget.id));setDeleting(null);setEdit(null);setScope('portfolio');setView('studio');setYear(0);notice('Проект удалён. Снимок для восстановления сохранён слева.');};
 const scenario=(price:number,speed:number,name:string,construction=a.construction)=>{const sid=id();s.setModel({...model,activeScenario:sid,scenarios:[...model.scenarios,{id:sid,name:p?`${p.name} · ${name}`:name,adjustments:{...a,price,speed,construction,projectId:scope==='portfolio'?undefined:scope}}]});notice('Сценарий сохранён и выбран')};
 const market=(patch:Partial<NonNullable<Project['market']>>)=>p&&update({...p,market:{...p.market!,...patch}});
 const setMonth=(key:'demand'|'prices',month:number,value:number)=>{if(!p)return;const values=[...p.market![key]];while(values.length<=month)values.push(100);values[month]=value;market({[key]:values})};
 if(!ready)return <div className="boot">Development Modeler 2.0</div>;
 return <div className="v-shell"><aside className="v-sidebar"><div className="v-brand"><Building2/><div>development<span>MODELER / 2.0</span></div></div><div className="v-caption">РАБОЧЕЕ ПРОСТРАНСТВО</div><label className="v-field v-model-picker"><span>Текущая модель</span><AppSelect aria-label="Текущая модель" value={model.id} onChange={e=>s.selectModel(e.target.value)}>{s.models.map(m=><option value={m.id} key={m.id}>{m.name}</option>)}</AppSelect></label><button className={view==='Models'?'v-nav active':'v-nav'} onClick={()=>setView('Models')}><Building2 size={18}/>Мои модели</button><button className={view==='Settings'?'v-nav active':'v-nav'} onClick={()=>setView('Settings')}><SlidersHorizontal size={18}/>Настройки модели</button><button className={scope==='portfolio'&&view==='studio'?'v-nav active':'v-nav'} onClick={()=>selectScope('portfolio')}><LayoutGrid size={18}/>Портфель</button><div className="v-caption">ПРОЕКТЫ <button aria-label="Добавить проект" onClick={add}><Plus size={16}/></button></div>{model.projects.map(q=><button className={`v-nav ${scope===q.id&&view==='studio'?'active':''}`} key={q.id} onClick={()=>selectScope(q.id)}><i style={{background:q.color}}/>{q.name}</button>)}<button className="v-nav subtle" onClick={add}><Plus size={17}/>Добавить проект</button><div className="v-caption">ОБЩИЕ РАСЧЁТЫ</div>{[['Timeline','Сроки',CalendarDays],['Cash Flow','Денежный поток',ChartNoAxesCombined],['Investments','Инвестиции',ChartNoAxesCombined],['Employees','Сотрудники',Users],['Costs','Расходы',SlidersHorizontal]].map(([key,label,Icon])=><button key={String(key)} className={`v-nav ${view===key?'active':''}`} onClick={()=>setView(String(key))}>{typeof Icon!=='string'&&<Icon size={18}/>} {String(label)}</button>)}<div className="v-side-bottom"><b>Автономная версия</b><p>Данные сохраняются в этом браузере. Резервная копия — кнопка вверху.</p><button className="v-nav" onClick={()=>{s.saveVersion('Снимок 2.0 · '+new Date().toLocaleString());notice('Снимок сохранён')}}><Save size={16}/>Сохранить снимок</button>{s.versions.filter(v=>v.model.id===model.id).slice(0,3).map(v=><button className="v-nav" key={v.id} onClick={()=>{s.saveVersion('До восстановления');s.restore(v.id);notice('Снимок восстановлен')}}><Undo2 size={14}/>{v.name}</button>)}</div></aside>
 <main className="v-main"><header className="v-top"><span>Финансовая модель <b>/ {model.name}</b></span><div><span className="v-saved">● Сохранено локально</span><button className="btn" onClick={()=>setSharing(true)}>Поделиться</button><button className="btn" onClick={()=>downloadBlob(new Blob([JSON.stringify(model,null,2)],{type:'application/json'}),'development-modeler-v2.json')}><Download size={15}/>Резервная копия</button></div></header><div className="v-content"><div className="v-heading"><div><div className="v-eyebrow">DEVELOPMENT INTELLIGENCE / 2.0</div><h1>{view==='studio'?(p?.name||'Портфель в перспективе'):({'Models':'Мои модели','Settings':'Настройки модели','Timeline':'График проектов','Cash Flow':'Денежный поток','Employees':'Команда','Costs':'Расходы','Investments':'Инвестиции и капитал'} as Record<string,string>)[view]}</h1><p>{p?'Параметры, продажи и экономика — в одном рабочем пространстве.':'Оцените экономику проектов при рыночных ценах, затратах и темпе продаж.'}</p></div><label className="v-field"><span>Сценарий</span><AppSelect aria-label="Сценарий" value={model.activeScenario} onChange={e=>{const selected=model.scenarios.find(x=>x.id===e.target.value);if(selected?.adjustments.projectId)setScope(selected.adjustments.projectId);s.setModel({...model,activeScenario:e.target.value})}}>{model.scenarios.map(x=><option key={x.id} value={x.id}>{tr(x.name)}</option>)}</AppSelect></label></div>
 {view==='Investments'?<InvestmentsView model={model} a={a} onChange={s.setModel} initialProject={p?.id||null}/>:view!=='studio'?<>{view!=='Models'&&view!=='Settings'&&<button className="btn" style={{marginBottom:16}} onClick={()=>setView('Investments')}>Инвестиции и денежный поток после выплат ↗</button>}{view==='Models'&&<ModelImport notify={notice}/>}<WorkspaceView key={model.id+view} model={model} view={view} a={a} onChange={s.setModel} navigate={v=>setView(v==='Overview'?'studio':v)} edit={(id,tab='Basic')=>setEdit({id,tab})} add={add} notify={notice}/></>:<>
 <div className="v-toolbar"><label>Начало модели <input aria-label="Начало модели" type="month" value={model.startDate.slice(0,7)} onChange={e=>e.target.value&&s.setModel({...model,startDate:e.target.value+'-01'})}/></label><span>{p?'1 проект':model.projects.length+' проекта'} · {result.units} объектов · {result.gla.toLocaleString('ru-RU')} м²</span>{p&&<div className="v-project-actions"><button className="btn" onClick={()=>setEdit({id:p.id,tab:'Basic'})}><SlidersHorizontal size={15}/>Все параметры проекта</button><button className="btn v-delete-project" onClick={()=>setDeleting(p.id)}><Trash2 size={15}/>Удалить проект</button></div>}</div>
 <p className="v-note" style={{marginBottom:16}}>{projectPeriod?`План проекта: М${projectPeriod.start}–М${projectPeriod.end} · ${projectPeriod.duration} мес.`:`Период портфеля: М1–М${result.months.length}`} · Расчёт: М{firstMonth}–М{result.months.length}{projectPeriod&&result.months.length>projectPeriod.end?' · После завершения этапов учтены оставшиеся продажи и платежи.':''}</p><div className="v-kpis">{[['Выручка за весь срок',fmt(result.revenue),'По договорам продаж'],['Маржа на выручку',(result.margin*100).toFixed(1)+'%',p?'До общих расходов компании':'С учётом расходов компании'],['Прибыль',fmt(result.profit),'За весь срок модели'],['Потребность в капитале',fmt(result.peak),result.peakMonth?tr(result.months[result.peakMonth-1]?.label||''):'Кассового разрыва нет']].map(([label,value,sub],i)=><section className={`v-kpi k${i}`} key={label}><span>{label}</span><strong>{value}</strong><small>{sub}</small></section>)}</div>
 {(model.investments||[]).some(i=>i.enabled)&&<div className="investment-strip"><span>Прибыль девелопера · портфель<b>{fmt(financing.developerProfit)}</b></span><span>Маржа после инвесторов<b>{(financing.developerMargin*100).toFixed(1)}%</b></span><span>Незакрытый дефицит<b>{fmt(financing.peak)}</b></span><button className="btn" onClick={()=>setView('Investments')}>Условия инвестиций ↗</button></div>}
 <div className="v-workgrid"><section className="v-card"><div className="v-section-title"><div><span className="v-eyebrow">01 / ПАРАМЕТРЫ</span><h2>{p?'Рыночные вводные проекта':'Проекты портфеля'}</h2></div></div>{p?<><div className="v-inputgrid"><Input label={`Рыночная цена остатка · ${model.currency}/м²`} min={1} value={Math.round(futurePrice(model,scope,{...a,price:0}).price)} onChange={price=>{const base=futurePrice(model,scope,{...a,price:0}).price;if(base>0)market({priceFactor:(p.market!.priceFactor??1)*price/base})}}/>
 {p.construction.mode==='Advanced'?<button className="btn" onClick={()=>setEdit({id:p.id,tab:'Construction'})}>Подробный бюджет строительства ↗</button>:<Input label={`Строительство · ${model.currency}/м²`} value={p.construction.costPerM2} onChange={costPerM2=>update({...p,construction:{...p.construction,mode:'Simple',costPerM2}})}/>}<Input label="Старт проекта · месяц модели" value={p.start} max={120} min={1} onChange={start=>update({...p,start:Math.round(start)})}/><Input label="Срок строительства · месяцев" value={p.timeline.constructionDuration} max={120} min={1} onChange={constructionDuration=>update({...p,timeline:{...p.timeline,constructionDuration:Math.round(constructionDuration)}})}/><Input label="Зафиксировано по месяц включительно" value={p.market!.lockedThrough} max={240} onChange={lockedThrough=>market({lockedThrough:Math.round(lockedThrough)})}/><Input label={`Доп. содержание до последней продажи · ${model.currency}/мес`} value={p.market!.holdingMonthly} onChange={holdingMonthly=>market({holdingMonthly})}/></div><p className="v-note">Базовая цена задаётся до сценарной поправки. Зафиксированные месяцы исключены из сценарного изменения цены и темпа. Дополнительное содержание добавляется к другим расходам с начала продаж.</p><div className="v-shortcuts">{[['Land','Земля'],['Sales','Юниты и продажи'],['Timeline','Сроки'],['Infrastructure','Инфраструктура'],['Costs','Затраты']].map(([tab,label])=><button className="btn" key={tab} onClick={()=>setEdit({id:p.id,tab})}>{label}<ArrowUpRight size={13}/></button>)}</div></>:<div className="v-projectlist">{model.projects.map(q=>{const r=scopedResult(model,q.id,a);return <button key={q.id} onClick={()=>selectScope(q.id)}><span><i style={{background:q.color}}/><b>{q.name}</b><small>{r.gla.toLocaleString('ru-RU')} м² · {projectWindow(q,a).duration} мес.</small></span><span><b>{(r.margin*100).toFixed(1)}%</b><small>Маржа проекта ↗</small></span></button>})}<button className="btn" onClick={add}><Plus size={15}/>Новый проект</button></div>}</section>
 <section className="v-card v-target v-stability" aria-label="Устойчивость проекта"><span className="v-eyebrow">02 / УСТОЙЧИВОСТЬ</span><h2>{p?'Устойчивость проекта':'Устойчивость портфеля'}</h2><p className="v-note">Цена и себестоимость — ваши рыночные вводные. Прибыль и маржа — результат расчёта.</p>{scope==='portfolio'&&<label className="v-field"><span>Какие расходы учитывать</span><AppSelect aria-label="Расчёт устойчивости" value={stabilityBasis} onChange={e=>setBasis(e.target.value as 'operating'|'developer')}><option value="operating">Расходы проектов и компании · до инвесторов</option><option value="developer">Также вознаграждение инвесторов</option></AppSelect></label>}
 <div className="v-stability-result"><span>Ожидаемая маржа · за весь срок</span><strong className={economicProfit<0?'negative':''}>{result.revenue?(economicMargin*100).toFixed(1)+'%':'Нет выручки'}</strong><p>{economicProfit<0?'Убыток':'Прибыль'}: <b>{fmt(Math.abs(economicProfit))}</b>{p?' · до общих расходов компании и инвесторов':stabilityBasis==='developer'?' · после вознаграждения инвесторов':' · до вознаграждения инвесторов'}</p></div>
 <div className="v-resilience-grid"><div><span>Цена в текущем сценарии</span><b>{current.area?fmt(current.price)+' / м²':'Нет оставшихся продаж'}</b><small>По {current.area.toLocaleString('ru-RU')} м² незафиксированных продаж</small></div><div><span>Цена безубыточности</span><b>{boundary.status==='ok'?fmt(boundary.price)+' / м²':boundary.status==='covered'?'Затраты уже покрыты':boundary.status==='no-inventory'?'Нет оставшихся продаж':'Не достигается'}</b><small>{boundary.status==='covered'?'Зафиксированная выручка покрывает учтённые расходы.':boundary.status==='unreachable'?'Повышение цены не покрывает расходы в пределах расчёта.':'Граница нулевой итоговой прибыли при остальных неизменных вводных'}</small></div><div><span>{boundary.cushion!==null&&boundary.cushion<0?'Цена ниже безубыточной':'Запас снижения цены до убытка'}</span><b className={boundary.cushion!==null&&boundary.cushion<0?'negative':''}>{boundary.cushion===null?'—':Math.abs(boundary.cushion).toFixed(1)+'%'}</b><small>{boundary.cushion!==null&&boundary.cushion<0?'Необходимый рост средней цены относительно текущей; это не рекомендация рынку.':'Снижение средней цены оставшихся продаж при неизменных затратах и темпе'}</small></div><div><span>{stabilityBasis==='developer'?'Незакрытый дефицит денег':'Максимальный дефицит денег'}</span><b>{fmt(funding.peak)}</b><small>{funding.peakMonth?tr(funding.months[funding.peakMonth-1]?.label||'')+' · за весь срок платежей':'Кассового разрыва нет'}{stabilityBasis==='developer'?' · с учётом взносов и выплат инвесторам':' · до привлечения инвестиций'}</small></div></div>
 <p className="v-note">Цена безубыточности — граница риска, а не предлагаемая цена продажи. {p?'Общие расходы компании и инвестиции оцениваются на уровне портфеля.':'Для портфеля цены оставшихся продаж изменяются пропорционально.'} Положительная итоговая прибыль не исключает кассового разрыва.</p></section></div>

 <section className="v-card v-overview-cash" aria-label="Накопленный денежный поток"><div className="v-section-title"><div><h2>Накопленный денежный поток</h2><p>{p?p.name:'Весь портфель'} · {p?'До общих расходов компании':'С учётом общих расходов компании'} · до финансирования и выплат инвесторам</p></div><span className="v-cash-legend"><i/>{tr(model.scenarios.find(s=>s.id===model.activeScenario)?.name||'Базовый')}</span></div><CashChart r={chartResult} currency={model.currency} scope={p?'project':'portfolio'}/><footer className="chart-footer"><span>Максимальный дефицит <b className={amountTone(-result.peak)}>{fmt(-result.peak)}</b></span><span>Остаток средств <b className={amountTone(result.months.at(-1)?.cumulative||0)}>{fmt(result.months.at(-1)?.cumulative||0)}</b></span></footer></section>
 <EconomicsChart result={result} currency={model.currency} projectName={p?.name}/>
 <section className="v-card v-matrix"><div className="v-section-title"><div><span className="v-eyebrow">03 / ЧУВСТВИТЕЛЬНОСТЬ</span><h2>{axis==='speed'?'Цена × темп продаж':'Цена × себестоимость строительства'}</h2><p>Изменения относительно выбранного сценария. Нажмите ячейку, чтобы сохранить новый сценарий. Сценарий проекта относится только к нему; переход к другому проекту или портфелю возвращает базовый сценарий.</p></div><div className="v-matrix-controls"><AppSelect aria-label="Фактор чувствительности" value={axis} onChange={e=>setAxis(e.target.value as 'speed'|'construction')}><option value="speed">Темп продаж</option><option value="construction">Себестоимость строительства</option></AppSelect><AppSelect aria-label="Показатель матрицы" value={metric} onChange={e=>setMetric(e.target.value)}><option value="margin">Маржа, %</option><option value="profit">Прибыль</option><option value="peak">Капитал до инвестиций</option>{scope==='portfolio'&&<><option value="developerMargin">Маржа после инвесторов</option><option value="fundingAfter">Капитал после инвестиций</option></>}</AppSelect></div></div><div className="table-scroll"><table className="v-matrix-table"><thead><tr><th>{axis==='speed'?'Темп':'Себестоимость'} ↓ / Цена за м² →</th>{[-20,-10,0,10,20].map(n=><th key={n}>{n>0?'+':''}{n}%<small>{fmt(current.price*(1+n/100))}/м²</small></th>)}</tr></thead><tbody>{cells.map((row,i)=><tr key={i}><th>{row[0].speed>0?'+':''}{row[0].speed}%<small>{axis==='speed'?(row[0].change<0?'Медленнее':row[0].change>0?'Быстрее':'Базовый темп'):(row[0].change<0?'Дешевле':row[0].change>0?'Дороже':'Базовая смета')}</small></th>{row.map(cell=><td key={cell.price}><button className={`${(metric==='developerMargin'||metric==='fundingAfter'?cell.financing?.developerProfit??cell.result.profit:cell.result.profit)>0?'good':(metric==='developerMargin'||metric==='fundingAfter'?cell.financing?.developerProfit??cell.result.profit:cell.result.profit)<0?'bad':'warn'} ${cell.price===0&&cell.speed===0?'baseline':''}`} onClick={()=>scenario(cell.adjustments.price,cell.adjustments.speed,`Цена ${cell.price>0?'+':''}${cell.price}% · ${axis==='speed'?'темп':'себестоимость'} ${cell.change>0?'+':''}${cell.change}%`,cell.adjustments.construction)}>{metric==='developerMargin'?(100*(cell.financing?.developerMargin??cell.result.margin)).toFixed(1)+'%':metric==='fundingAfter'?fmt(cell.financing?.peak??cell.result.peak):metric==='margin'?(cell.result.margin*100).toFixed(1)+'%':fmt(metric==='profit'?cell.result.profit:cell.result.peak)}<small>{cell.financing?.duration??cell.result.duration} мес.</small></button></td>)}</tr>)}</tbody></table></div><p className="v-note">Зелёный — положительная прибыль · бежевый — нулевая маржа · красный — убыток. Цвет показывает знак прибыли, а не привлекательность проекта. Себестоимость меняет затраты строительства и инфраструктуры. Темп сдвигает продажи и поступления; дополнительные расходы растут, только если заданы в модели.</p></section>
 <section className="v-card"><div className="v-section-title"><div><span className="v-eyebrow">04 / ПОМЕСЯЧНЫЙ ПЛАН</span><h2>Сезонность и движение денег</h2><p>{p?'100% — базовый уровень. 0% спроса — пауза продаж. После заполненного периода действует 100%.':'Выберите проект слева, чтобы настроить спрос и цену по месяцам.'}</p></div><AppSelect aria-label="Период плана" value={activeYear} onChange={e=>setYear(Number(e.target.value))}><option value={-1}>{p?'Весь срок проекта':'Весь срок портфеля'}</option>{Array.from({length:pageCount},(_,i)=><option key={i} value={i}>Месяцы {displayMonths[i*12]?.month}–{displayMonths[Math.min(i*12+11,displayMonths.length-1)]?.month}</option>)}</AppSelect></div><div className="table-scroll"><table className="v-months"><thead><tr><th>Показатель</th>{planMonths.map(m=><th key={m.month}>{tr(m.label)}<small>М{m.month}</small></th>)}</tr></thead><tbody>{p&&(['demand','prices'] as const).map(key=><tr key={key}><th>{key==='demand'?'Спрос, % к базе':'Цена, % к базе'}</th>{planMonths.map(m=><td key={m.month}><NumberInput aria-label={`${key==='demand'?'Спрос':'Цена'} М${m.month}`} value={p.market![key][m.month-1]??100} min={0} max={500} disabled={m.month<=p.market!.lockedThrough} onChange={e=>setMonth(key,m.month-1,Math.max(0,Math.min(500,+e.target.value)))}/></td>)}</tr>)}{[['Продано объектов','units'],['Договоры','contracts'],['Поступления','inflow'],['Расходы','outflow'],['Накопленный поток','cumulative']].map(([label,key])=><tr key={key}><th>{label}</th>{planMonths.map(m=><td key={m.month} className={Number(m[key as keyof typeof m])<0?'negative':''}>{key==='units'?m.units:fmt(Number(m[key as keyof typeof m]))}</td>)}</tr>)}</tbody></table></div></section>
 <details className="v-card v-method"><summary>Дополнительно · стоимость денег во времени</summary><p>NPV оценивает денежный поток с учётом времени поступлений и расходов. Ставка ниже влияет только на NPV, не на маржу и цену безубыточности.</p><Input label="Ставка дисконтирования · % годовых" value={discount} max={100} onChange={setDiscount}/><p>NPV до финансирования: <strong>{fmt(npv(result,discount))}</strong></p></details>
 <details className="v-card v-method"><summary>Методика и проверка модели · {result.warnings.length} замечаний</summary><p>Маржа = (выручка − все учтённые затраты) / выручка. Доходность на затраты = прибыль / затраты. Портфельная маржа рассчитана по сумме денег, а не как среднее процентов проектов. NPV — месячный денежный поток до финансирования, дисконтированный на конец месяца; начальный баланс равен нулю.</p><p>Это управленческая экономика за весь срок, не бухгалтерская прибыль по месяцам. Инвестиции, проценты и распределения прибыли рассчитываются отдельно в разделе «Инвестиции»; эта операционная таблица их не включает. Налоги включаются только через заданные статьи расходов. Валюта единая, автоматической конвертации нет. План расширяется до завершения платежей; четыре года — окно просмотра, а не обрезка обязательств.</p><p>Фиксация месяцев защищает базовые сделки от сценарных изменений. Она не заменяет журнал фактических договоров: прямое редактирование исходных параметров меняет базовую модель.</p><a href="https://www.rics.org/profession-standards/rics-standards-and-guidance/sector-standards/valuation-standards/valuation-of-development-property" target="_blank" rel="noreferrer">Принципы оценки девелоперских проектов · RICS</a>{result.warnings.map((w,i)=><p key={i} className="v-warning">{tr(w)}</p>)}</details>
 </> }</div></main><Dialog open={!!edit} onOpenChange={v=>!v&&setEdit(null)} title="Параметры проекта" wide>{edit&&model.projects.find(q=>q.id===edit.id)&&<ProjectEditor key={edit.id+edit.tab} startDate={model.startDate} project={model.projects.find(q=>q.id===edit.id)!} initial={edit.tab} a={a} onChange={update}/>}</Dialog><Dialog open={!!deleteTarget} onOpenChange={open=>!open&&setDeleting(null)} title="Удалить проект?"><div className="v-delete-confirm"><p>Проект <strong>«{deleteTarget?.name}»</strong> будет удалён из портфеля вместе с его юнитами, инфраструктурой, затратами, сценариями и привязанными инвестициями.</p><p>Общие расходы, сотрудники и инвестиции портфеля сохранятся.</p><p className="v-delete-backup">Перед удалением автоматически сохраним снимок всей модели. Восстановить его можно в левом меню; это вернёт всю модель к состоянию до удаления.</p><div className="v-project-actions"><button autoFocus className="btn" onClick={()=>setDeleting(null)}>Отмена</button><button className="btn v-delete-solid" onClick={confirmDelete}>Удалить проект</button></div></div></Dialog><Dialog open={sharing} onOpenChange={setSharing} title="Поделиться моделью"><ShareModel key={model.id} model={model}/></Dialog>{toast&&<div className="toast" role="status">{toast}</div>}</div>
}
