'use client';
import {AppSelect} from '@/components/ui/app-select';
import {NumberInput} from './number-input';
import {tr,useLanguage} from '@/lib/i18n';
import {Switch as S,Slider as SL} from 'radix-ui';
export function Field({label,value,onChange,type='text',min=0,max,step,help}:{label:string;value:string|number;onChange:(v:any)=>void;type?:string;min?:number;max?:number;step?:number;help?:string}){useLanguage();return <label className="field"><span>{tr(label)}</span>{type==='number'?<NumberInput value={value} min={min} max={max} step={step??'any'} onChange={e=>{const n=Number(e.target.value);if(Number.isFinite(n))onChange(Math.max(min,Math.min(max??1e12,step===1?Math.round(n):n)))}}/>:<input type={type} value={value} onChange={e=>onChange(e.target.value)}/>}{help&&<small>{help}</small>}</label>}
export function Select({label,value,options,onChange}:{label:string;value:string;options:string[];onChange:(v:any)=>void}){useLanguage();return <label className="field"><span>{tr(label)}</span><AppSelect value={value} onChange={e=>onChange(e.target.value)}>{options.map(v=><option key={v} value={v}>{tr(v)}</option>)}</AppSelect></label>}
export function Toggle({label,checked,onChange}:{label:string;checked:boolean;onChange:(v:boolean)=>void}){useLanguage();return <label className="toggle-row"><span>{tr(label)}</span><S.Root checked={checked} onCheckedChange={onChange} className="switch" aria-label={tr(label)}><S.Thumb className="switch-thumb"/></S.Root></label>}
export function Slider({label,value,min,max,onChange,suffix='%'}:{label:string;value:number;min:number;max:number;onChange:(v:number)=>void;suffix?:string}){useLanguage();return <div className="slider-field"><div><span>{tr(label)}</span><strong>{tr(value>0?'+':'')}{value}{suffix}</strong></div><SL.Root className="slider" min={min} max={max} step={1} value={[value]} onValueChange={v=>onChange(v[0])} aria-label={tr(label)}><SL.Track className="slider-track"><SL.Range className="slider-range"/></SL.Track><SL.Thumb className="slider-thumb"/></SL.Root></div>}
