'use client';
import {AppSelect} from '@/components/ui/app-select';
import {amountTone,financialColors} from '@/lib/financial-colors';
import {tr,useLanguage} from '@/lib/i18n';
import {useState,useMemo} from 'react';
import {useReactTable,getCoreRowModel,flexRender,ColumnDef} from '@tanstack/react-table';
import {FinancialModel,Adjustments,Result} from '@/types/model';
import {calculatePortfolioCashFlow,projectWindow} from '@/lib/financial-engine';
import {CashChart} from '@/features/models/dashboard';
import {money as formatMoney,number,percent} from '@/lib/format';
interface Row {label:string;values:number[];total:boolean}
export function FinancialTable({r,pnl=false,currency='USD'}:{r:Result;pnl?:boolean;currency?:string}){useLanguage();const money=(n:number,c=false)=>formatMoney(n,c,currency);const rows:Row[]=useMemo(()=>pnl?[{label:'Development revenue · contract value',values:[r.revenue],total:true},...Object.entries(r.costs).map(([label,v])=>({label,values:[v],total:false})),{label:'TOTAL DEVELOPMENT COST',values:[r.cost],total:true},{label:'DEVELOPMENT PROFIT',values:[r.profit],total:true},{label:'MARGIN',values:[r.margin],total:true}]:[{label:'TOTAL INFLOW',values:r.months.map(m=>m.inflow),total:true},...['Full Cash Collections','Installment Collections','Normal Price Collections'].map(label=>({label,values:r.months.map(m=>m.collections[label]||0),total:false})),{label:'TOTAL OUTFLOW',values:r.months.map(m=>m.outflow),total:true},...Object.keys(r.costs).map(label=>({label,values:r.months.map(m=>m.categories[label]||0),total:false})),{label:'NET CASH FLOW',values:r.months.map(m=>m.net),total:true},{label:'CUMULATIVE CASH FLOW',values:r.months.map(m=>m.cumulative),total:true}],[r,pnl]);const columns:ColumnDef<Row>[]=useMemo(()=>[{accessorKey:'label',header:tr(pnl?'P&L · lifetime economics':'Cash flow · '+currency),cell:info=>tr(String(info.getValue()))},...(pnl?['Total']:r.months.map(m=>m.label)).map((label,i)=>({id:String(i),header:tr(label),cell:({row}:{row:{original:Row}})=>row.original.label==='MARGIN'?percent(row.original.values[i]):money(row.original.values[i])})),...(pnl?[{id:'revenueShare',header:tr('% of revenue'),cell:({row}:{row:{original:Row}})=>row.original.label==='MARGIN'||r.revenue===0?'—':percent(row.original.values[0]/r.revenue)}]:[])],[r,pnl,currency,useLanguage.getState().language]);const expenseLabels=new Set(['TOTAL OUTFLOW','TOTAL DEVELOPMENT COST',...Object.keys(r.costs)]);const table=useReactTable({data:rows,columns,getCoreRowModel:getCoreRowModel()});return <div className="table-scroll"><table className="data-table financial-table"><thead>{table.getHeaderGroups().map(g=><tr key={g.id}>{g.headers.map(h=><th key={h.id} className={!pnl&&r.months[+h.id]?.month===r.peakMonth?'highlight':''}>{flexRender(h.column.columnDef.header,h.getContext())}</th>)}</tr>)}</thead><tbody>{table.getRowModel().rows.map(row=><tr key={row.id} className={row.original.total?'total':''}>{row.getVisibleCells().map((cell,i)=><td key={cell.id} className={`${i>0?amountTone(row.original.values[pnl?0:i-1],expenseLabels.has(row.original.label)?'expense':'balance'):''} ${!pnl&&r.months[i-1]?.month===r.peakMonth?'highlight':''}`}>{flexRender(cell.column.columnDef.cell,cell.getContext())}</td>)}</tr>)}</tbody></table></div>}
export function CashFlowView({model,a,pnl=false}:{model:FinancialModel;a:Adjustments;pnl?:boolean}){useLanguage();const money=(n:number,c=false)=>formatMoney(n,c,model.currency);const [pid,setPid]=useState('all');const all=calculatePortfolioCashFlow(model,a);const selectedProject=model.projects.find(p=>p.id===pid),raw=pid==='all'?all:all.projects[model.projects.findIndex(p=>p.id===pid)]||all;const firstMonth=selectedProject?Math.min(projectWindow(selectedProject,a).start,...raw.months.filter(m=>m.inflow!==0||m.outflow!==0||m.units!==0).map(m=>m.month)):1;const r={...raw,months:raw.months.filter(m=>m.month>=firstMonth)};return <><div className="view-title"><div><h1>{tr(pnl?'Profit & loss':'Cash flow')}</h1><p>{tr(pnl?'Lifetime development economics, with project and consolidated views.':'Monthly collections, obligations and capital requirements.')}</p></div><AppSelect aria-label={tr("Project scope")} value={pid} onChange={e=>setPid(e.target.value)}><option value="all">{tr("Consolidated portfolio")}</option>{model.projects.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</AppSelect></div><div className="kpi-grid">{[{label:pnl?'Revenue':'Total collections',value:money(r.revenue,true)},{label:pnl?'Development cost':'Peak funding',value:money(pnl?r.cost:r.peak,true)},{label:pnl?'Development profit':'Peak funding month',value:pnl?money(r.profit,true):r.peakMonth?`M${r.peakMonth}`:'None'},{label:pnl?'Margin':'Closing cash',value:pnl?percent(r.margin):money(r.months.at(-1)?.cumulative||0,true)}].map((k,i)=><div className="kpi" key={tr(k.label)}><div>{tr(k.label)}</div><strong className={amountTone(i===0?r.revenue:i===1?(pnl?r.cost:r.peak):i===2?(pnl?r.profit:0):(pnl?r.margin:r.months.at(-1)?.cumulative||0),i===1?(pnl?'expense':'funding'):'balance')}>{k.value}</strong></div>)}</div>{!pnl&&<section className="card" style={{marginBottom:20}}><CashChart r={{...r,projects:all.projects}} monthly currency={model.currency}/></section>}<section className="card">{pnl&&<p className="pnl-share-note">{tr("% of revenue = line amount ÷ contracted revenue for the selected scope. No percentage is shown when revenue is zero.")}</p>}<FinancialTable r={r} pnl={pnl} currency={model.currency}/></section><p className="notice">{tr(pnl?'Management P&L uses sales contract value over the full project lifecycle. It is not a statutory revenue-recognition statement.':'Период определяется сроками этапов и всех запланированных платежей. Выделен месяц максимального дефицита; платежи после передачи объекта сохранены.')}</p></>}
