export const ru:Record<string,string>={
'Architecture':'Проектирование','Marketing Preparation':'Подготовка маркетинга',
'Infrastructure':'Инфраструктура','Other construction':'Прочие строительные работы',
'Infrastructure budget':'Бюджет инфраструктуры','Facility name':'Название объекта','Construction cost / m²':'Себестоимость строительства / м²',
'Add a gym, restaurant or other shared facility. Its budget is added to this project; its area is not included in saleable units.':'Добавьте спортзал, ресторан или другой объект. Его бюджет включается в затраты этого проекта, а площадь учитывается отдельно от продаваемых юнитов.',
'Exclude these amounts from the main construction budget to avoid counting them twice.':'В основной стоимости строительства эти расходы учитывать повторно не нужно.',
'No infrastructure facilities yet':'Объекты инфраструктуры пока не добавлены','Add a facility and enter its area, construction cost and schedule.':'Добавьте объект и укажите площадь, себестоимость и сроки строительства.',
'Infrastructure facility':'Объект инфраструктуры','Remove infrastructure facility':'Удалить объект инфраструктуры',
'Start · model month':'Начало · месяц модели','The start moves with main construction. Duration remains independent.':'При переносе основного строительства старт объекта сдвинется вместе с ним. Длительность задаётся отдельно.',
'Facility budget':'Бюджет объекта','This facility finishes after project handover. Adjust its schedule or the handover date in Timeline.':'Строительство объекта заканчивается после передачи проекта. Скорректируйте его сроки или дату передачи во вкладке «Таймлайн».',
'New infrastructure facility':'Новый объект','Add infrastructure facility':'Добавить объект','Infrastructure total':'Всего инфраструктура',
'Construction scenarios also apply to infrastructure prices. Costs calculated as a percentage of construction include this budget.':'Сценарная поправка к стоимости строительства действует и на инфраструктуру. Затраты в процентах от строительства рассчитываются с учётом этого бюджета.',

'Overview':'Обзор','Projects':'Проекты','Timeline':'Таймлайн','Land':'Земля','Sales':'Продажи','Construction':'Строительство','Costs':'Затраты','Employees':'Сотрудники','Cash Flow':'Денежный поток','P&L':'Прибыли и убытки','Scenarios':'Сценарии','Reports':'Отчёты','Settings':'Настройки','Basic':'Основное','Unit Mix':'Типы юнитов','Pricing':'Цены','Models':'Модели',
'WORKSPACE':'РАБОЧЕЕ ПРОСТРАНСТВО','Development workspace':'Рабочее пространство','Quick search':'Быстрый поиск','Model health':'Проверка модели','Workspace owner':'Владелец','Financial models':'Финансовые модели','Warnings':'Замечания','Scenario':'Сценарий','Export':'Экспорт','Share':'Поделиться','Saved locally':'Сохранено на устройстве','Local workspace':'Локальная модель','Project assumptions':'Параметры проекта','Add development project':'Добавить проект','Share financial model':'Поделиться моделью','Quick command':'Быстрые действия','Search pages and actions…':'Поиск разделов и действий…','No model warnings.':'Замечаний нет.','Go to':'Перейти в','All figures in':'Все суммы в','· Monthly financial model':'· Помесячная финансовая модель',
'PORTFOLIO OVERVIEW':'ОБЗОР ПОРТФЕЛЯ','Your portfolio, in perspective.':'Ваш портфель в цифрах.','View timeline':'Открыть таймлайн','Total revenue':'Общая выручка','Contracted development sales':'Выручка по договорам продаж','Development profit':'Прибыль девелопмента','Development cost':'Затраты девелопмента','Peak funding need':'Потребность в финансировании','Cumulative cash flow':'Накопленный денежный поток','Capital deployed. Value created.':'Движение капитала и создание стоимости.','Funding trough':'Максимальный дефицит','Closing cash balance':'Остаток средств','Revenue by project':'Выручка по проектам','Average selling price':'Средняя цена продажи','Revenue / m²':'Выручка / м²','Development roadmap':'План реализации','From land control to handover':'От земли до передачи объекта','Open timeline':'Открыть таймлайн','Monthly sales':'Продажи по месяцам','Units contracted across the portfolio':'Проданные юниты по всему портфелю','Open sales':'Открыть продажи','Sales calendar year':'Год продаж','Total units sold in':'Всего продано за','January–December':'Январь–декабрь','Cost composition':'Структура затрат','Where your capital goes':'Распределение капитала','What if?':'Что, если?','Explore the impact. Every change updates your active scenario.':'Каждое изменение пересчитывает активный сценарий.','Reset':'Сбросить','Your projects':'Ваши проекты','Add project':'Добавить проект','Revenue':'Выручка','Profit':'Прибыль','Cost':'Затраты','Margin':'Маржа','Units':'Юниты','Sales price':'Цена продажи','Construction cost':'Стоимость строительства','Sales speed':'Темп продаж','PBG delay':'Задержка PBG','Land cost':'Стоимость земли','Price':'Цена','Units sold':'Продано юнитов','Net cash flow':'Чистый денежный поток',
'Project name':'Название проекта','Location':'Локация','Country':'Страна','Project type':'Тип проекта','Status':'Статус','Project start · model month':'Старт проекта · месяц модели','Currency · match portfolio reporting':'Валюта · как в портфеле','Land price calculation':'Расчёт стоимости земли','Manual':'Вручную','Leasehold':'Лизхолд','Land area':'Площадь земли','Area unit':'Единица площади','Leasehold term · years':'Срок лизхолда · лет','Land area · are / сотки':'Площадь земли · сотки','Price per are per year · IDR':'Цена сотки за год · IDR','Exchange rate · IDR per 1 USD':'Курс · IDR за 1 USD','Your model assumption; no live rate is applied.':'Курс задаётся вручную для этой модели.','1 are = 1 сотка = 100 m²':'1 сотка = 100 м²','Payment type':'Тип оплаты','Land control · project month':'Контроль земли · месяц проекта','Down payment · %':'Первоначальный платёж · %','Installment count':'Количество платежей','Frequency · months':'Периодичность · месяцев','First installment · project month':'Первый платёж · месяц проекта','PBG may start after initial payment / land control':'PBG может начинаться после первого платежа / контроля земли','Add payment':'Добавить платёж','Project month':'Месяц проекта','Amount · $':'Сумма · $','Full Payment':'Полная оплата','Installments':'Рассрочка','Custom Schedule':'Свой график','Land total · USD:':'Стоимость земли · USD:','Land total cost · USD':'Стоимость земли · USD','Enter exchange rate':'Укажите курс','Custom payment amounts are entered separately and must match the calculated total.':'Суммы собственного графика вводятся отдельно и должны совпадать с итоговой ценой.','The IDR → USD leasehold calculator is available for projects in USD.':'Калькулятор IDR → USD доступен для проектов в USD.',
'PBG start offset':'Смещение старта PBG','PBG duration · months':'Длительность PBG · месяцев','Sales start offset':'Смещение старта продаж','Sales duration · months':'Длительность продаж · месяцев','Construction start offset':'Смещение старта стройки','Construction duration · months':'Длительность стройки · месяцев','Handover after completion · months':'Передача после завершения · месяцев','Sales timing relative to PBG end':'Сроки продаж относительно окончания PBG','Construction timing relative to PBG end':'Сроки стройки относительно окончания PBG','Negative values allow a start before the anchor.':'Отрицательное значение позволяет начать раньше опорной даты.','Start dependency':'Опорная дата','Offset · months':'Смещение · месяцев','Duration · months':'Длительность · месяцев','Project Start':'Старт проекта','Fixed Month':'Фиксированный месяц','PBG Start':'Начало PBG','PBG End':'Окончание PBG','Sales Start':'Старт продаж','Construction Start':'Старт стройки','Handover':'Передача объекта','Development timeline':'Таймлайн проекта','Timeline horizon':'Горизонт таймлайна','Project start':'Старт проекта','Stage':'Этап','Sales and construction start after PBG by default. Drag them earlier to overlap PBG; the offset follows future PBG changes.':'По умолчанию продажи и стройка начинаются после PBG. Их можно сдвинуть раньше; смещение сохраняется при изменении PBG.',
'Unit type':'Тип юнита','Unit area':'Площадь юнита','Unit quantity':'Количество юнитов','Area · m²':'Площадь · м²','Quantity':'Количество','Add unit type':'Добавить тип юнита','Pricing tier':'Ценовая категория','Price · $':'Цена · $','Buyer plan':'План оплаты','Add tier':'Добавить категорию','Tier name':'Название категории','Tier price':'Цена категории','Tier units':'Юниты категории','Buyer plan type':'Тип оплаты покупателем','Unit allocation does not match inventory.':'Распределение юнитов не совпадает с их количеством.','Sales plan mode':'Режим плана продаж','AUTO':'Автоматически','MANUAL':'Вручную','Distribution':'Распределение','Custom distribution weights · comma separated':'Веса распределения · через запятую','Even':'Равномерно','Front Loaded':'Больше в начале','Back Loaded':'Больше в конце','S-Curve':'S-кривая','Custom':'Свой вариант','Start offset after sales start':'Смещение от старта продаж','Sales window · months':'Период продаж · месяцев','Buyer payment plan':'План оплаты покупателем','Full Cash':'Полная оплата','Installment':'Рассрочка','At signing · %':'При подписании · %','Maximum installment term':'Максимальный срок рассрочки','Finish payments by':'Завершить оплату к','Construction Completion':'Завершение стройки','Fixed Date':'Фиксированная дата','No Restriction':'Без ограничения','Final payment · model month':'Последний платёж · месяц модели','Monthly unit sales':'Продажи юнитов по месяцам','Scroll horizontally to view all months':'Прокрутите по горизонтали, чтобы увидеть все месяцы','Offsets are months after signing. Payments must sum to 100%.':'Смещение в месяцах после подписания. Сумма платежей должна быть 100%.','Offset':'Смещение','Payment · %':'Платёж · %','Add payment milestone':'Добавить этап оплаты',
'Cost mode':'Режим расчёта','Construction cost / m² · $':'Стоимость стройки / м² · $','Spend curve':'График расходов','Monthly percentages · comma separated · total 100%':'Проценты по месяцам · через запятую · сумма 100%','Construction category':'Категория строительства','Budget · $':'Бюджет · $','Add construction category':'Добавить категорию','Simple':'Простой','Advanced':'Подробный','Add development cost':'Добавить затраты','Cost driver':'База расчёта','Timing':'Сроки','Duration':'Длительность','Linked timeline stage':'Связанный этап','Name':'Название','Type':'Тип','Monthly amounts · comma separated':'Суммы по месяцам · через запятую','One-Time':'Разово','Monthly':'Ежемесячно','Fixed':'Фиксированно','Project scope':'Охват проектов','Allocation method':'Метод распределения','Company operating costs':'Операционные расходы компании','Shared operating resources':'Общие операционные ресурсы','Office, software and other non-staff resources. Manage all salaries in Employees.':'Офис, ПО и другие ресурсы. Зарплаты находятся в разделе «Сотрудники».','Add cost':'Добавить расход','Add resource':'Добавить ресурс','Equal':'Поровну','By Revenue':'По выручке','By Units':'По юнитам','By GLA':'По площади','Manual %':'Вручную · %','Corporate':'Компания',
'PEOPLE & DEPARTMENTS':'СОТРУДНИКИ И ОТДЕЛЫ','One company team across all projects. Salaries follow each department’s working period.':'Единая команда для всех проектов. Зарплата начисляется за период работы отдела.','Department timeline':'Таймлайн отделов','Add department':'Добавить отдел','Total payroll budget':'Общий бюджет ФОТ','Entire model · all departments':'Вся модель · все отделы','Management, sales and construction teams':'Руководство, продажи и строительство','Departments':'Отделы','Each with its own working period':'У каждого свой период работы','Peak monthly payroll':'Пиковый месячный ФОТ','Based on overlapping work periods':'С учётом пересечения периодов работы','Payroll is paid from the department’s first working month through its last, inclusive. Move or resize the department in Timeline to change the payment period.':'Зарплата начисляется с первого по последний месяц работы отдела включительно. Изменяйте период отдела в таймлайне.','Work period':'Период работы','Monthly payroll':'Месячный ФОТ','Department budget':'Бюджет отдела','Department name':'Название отдела','Working duration · months':'Длительность работы · месяцев','Employee name · optional':'Имя сотрудника · необязательно','Role / position':'Должность','Total salary':'Всего зарплата','Add employee':'Добавить сотрудника','Add employees to calculate this department’s payroll.':'Добавьте сотрудников для расчёта ФОТ отдела.','Move employee to another department':'Перевести сотрудника в другой отдел','Build your development team':'Сформируйте команду','Add a department, set its working period, then add employees.':'Добавьте отдел, задайте период работы и сотрудников.','New department':'Новый отдел','Create department':'Создать отдел','Departments · salary periods':'Отделы · периоды зарплат','Move or resize to adjust payroll':'Сдвигайте или меняйте длительность для пересчёта ФОТ','Portfolio / company':'Портфель / компания','Management':'Руководство','Marketing':'Маркетинг','Payroll':'Фонд оплаты труда',
'Model settings':'Настройки модели','Model identity, saved versions and cloud workspace.':'Параметры модели, история версий и облачное хранение.','Model name':'Название модели','Model start date':'Дата начала модели','Reporting currency · no FX conversion':'Валюта отчётности · без конвертации','Version history':'История версий','Load cloud versions':'Загрузить версии из облака','Version name':'Название версии','Save version':'Сохранить версию','Restore':'Восстановить','Cloud workspace · Supabase':'Облачное хранилище · Supabase','Email':'Электронная почта','Password':'Пароль','Sign in':'Войти','Create account':'Создать аккаунт','Sign out':'Выйти','Save models to cloud':'Сохранить модели в облако','Load cloud models':'Загрузить модели из облака','Portable model backup':'Резервная копия модели','Save a complete JSON backup to move your model between devices.':'Сохраните полную копию JSON для переноса модели между устройствами.','Download model backup':'Скачать копию модели','Open Supabase':'Открыть Supabase','Create a Supabase project.':'Создайте проект Supabase.','Models are currently saved on this device. Cloud authentication and synchronization require your Supabase project.':'Модели хранятся на этом устройстве. Для облачной синхронизации подключите Supabase.',
'Investment reports':'Инвестиционные отчёты','Your model, ready for the investment conversation.':'Ваша модель для обсуждения инвестиций.','Excel financial model':'Финансовая модель Excel','Investment report · PDF':'Инвестиционный отчёт · PDF','Preview report':'Предпросмотр отчёта','Export Excel':'Экспорт Excel','Export PDF':'Экспорт PDF','Read-only model link':'Ссылка только для просмотра','Create read-only link':'Создать ссылку для просмотра','Copy link':'Копировать ссылку','A read-only link shows the last cloud-saved model. Anyone with the link can view it for 7 days.':'Ссылка открывает последнюю сохранённую облачную модель. Доступ по ссылке действует 7 дней.','Connect Supabase in Settings and save this model to cloud to create a sharing link.':'Подключите Supabase в настройках и сохраните модель в облако для создания ссылки.','Scenario studio':'Редактор сценариев','Compare the economics before committing capital.':'Сравните финансовые результаты сценариев.','Active scenario name':'Название активного сценария','Duplicate active scenario':'Дублировать активный сценарий','Consolidated portfolio':'Весь портфель','Select project':'Выбрать проект','Edit project':'Редактировать проект','Your development investment workspace.':'Ваше пространство для инвестиционных моделей.','New Financial Model':'Новая финансовая модель','Your first development starts here':'Начните первый проект','Add land, units and a timeline to build your financial model.':'Добавьте землю, юниты и сроки, чтобы построить модель.','Add a project to begin.':'Добавьте проект, чтобы начать.','Edit assumptions to update your financial model instantly.':'Изменяйте параметры — модель пересчитывается сразу.','Development projects':'Девелоперские проекты','Development costs':'Затраты девелопмента','Sales & buyer payments':'Продажи и платежи покупателей','Project costs':'Расходы проекта','Back':'Назад','Continue':'Продолжить','Create project':'Создать проект','Close':'Закрыть','Base':'Базовый','Optimistic':'Оптимистичный','Conservative':'Консервативный','Peak funding':'Потребность в финансировании','GLA · m²':'Полезная площадь · м²','PROJECT':'ПРОЕКТ','PBG / Permits':'PBG / Разрешения',
'14 structured worksheets. Assumptions, project schedules, buyer collections, monthly cash flow and P&L, with formulas and investment model formatting.':'14 листов: параметры, графики проектов, платежи покупателей, денежный поток и прибыль, с формулами и оформлением.','A dedicated report with executive summary, project economics, sales, land payments, capital requirement and scenario comparison.':'Отчёт с основными показателями, экономикой проектов, продажами, платежами за землю, финансированием и сравнением сценариев.'
};
Object.assign(ru,{'projects':'проектов','projects ·':'проектов ·','units':'юнитов','units ·':'юнитов ·','m² GLA':'м² полезной площади','month lifecycle':'месяцев реализации','margin':'маржа','· Margin':'· Маржа','per m²':'за м²','profit margin':'маржа прибыли','No funding gap':'Дефицита средств нет','Total':'Итого','None':'Нет','Preparing…':'Подготовка…','Profit & loss':'Прибыли и убытки','Cash flow':'Денежный поток','Total collections':'Всего поступлений','Peak funding month':'Месяц пикового дефицита','Closing cash':'Остаток средств','TOTAL INFLOW':'ВСЕГО ПОСТУПЛЕНИЙ','TOTAL OUTFLOW':'ВСЕГО ВЫПЛАТ','NET CASH FLOW':'ЧИСТЫЙ ДЕНЕЖНЫЙ ПОТОК','CUMULATIVE CASH FLOW':'НАКОПЛЕННЫЙ ДЕНЕЖНЫЙ ПОТОК','TOTAL DEVELOPMENT COST':'ВСЕГО ЗАТРАТ','DEVELOPMENT PROFIT':'ПРИБЫЛЬ ДЕВЕЛОПМЕНТА','MARGIN':'МАРЖА','Development revenue · contract value':'Выручка по договорам','Full Cash Collections':'Поступления полной оплаты','Installment Collections':'Поступления рассрочки','Normal Price Collections':'Поступления по обычной цене','Land Payments':'Платежи за землю','Sales Commission':'Комиссия продаж','Taxes':'Налоги','P&L · lifetime economics':'Прибыль за весь проект','Lifetime development economics, with project and consolidated views.':'Экономика за весь срок: по проектам и по портфелю.','Monthly collections, obligations and capital requirements.':'Помесячные поступления, обязательства и потребность в капитале.','Management P&L uses sales contract value over the full project lifecycle. It is not a statutory revenue-recognition statement.':'Управленческий отчёт учитывает стоимость договоров за весь срок проекта.','The highlighted column is the lowest cumulative cash balance. The calculation extends beyond the selected horizon to include all scheduled payments.':'Выделен месяц максимального дефицита. Расчёт включает все запланированные платежи, в том числе за пределами выбранного горизонта.','Jan':'Янв','Feb':'Фев','Mar':'Мар','Apr':'Апр','May':'Май','Jun':'Июн','Jul':'Июл','Aug':'Авг','Sep':'Сен','Oct':'Окт','Nov':'Ноя','Dec':'Дек','Configured':'Подключено','Not configured':'Не подключено','Saving…':'Сохранение…','Cloud saved':'Сохранено в облаке','Save to cloud':'Сохранить в облако','Project created.':'Проект создан.','Version saved.':'Версия сохранена.','Add Project':'Добавить проект','Duplicate Project':'Дублировать проект','Add Cost':'Добавить расход','Create Scenario':'Создать сценарий','Hypothesis':'Гипотеза','Land Selected':'Земля выбрана','Land Secured':'Земля закреплена','Completed':'Завершён','Villa':'Вилла','Apartment':'Апартаменты','Townhouse':'Таунхаус','Hotel':'Отель','Mixed':'Смешанный','are':'сотки','hectare':'гектары','Employee':'Сотрудник','Monthly salary ·':'Месячная зарплата ·','Working period':'Период работы','All salaries are company expenses, without project allocation.':'Все зарплаты — расходы компании без распределения по проектам.','employees':'сотрудников','Company':'Компания'});
Object.assign(ru,{'Open financial models':'Открыть финансовые модели','Remove payment':'Удалить платёж','Remove unit type':'Удалить тип юнита','Remove pricing tier':'Удалить ценовую категорию','Remove buyer payment':'Удалить платёж покупателя','Remove construction category':'Удалить категорию строительства','Remove development cost':'Удалить расход','Remove corporate cost':'Удалить расход компании','Remove shared resource':'Удалить общий ресурс','Land control M':'Контроль земли М','· PBG starts M':'· PBG начинается М','· Total scheduled':'· Всего платежей','→ Sales M':'→ Продажи М','→ Construction M':'→ Строительство М','→ Handover M':'→ Передача М','Allocated':'Распределено','model warnings':'замечаний к модели','Move a stage or resize its edges. Linked activities and cash flow follow. M1 =':'Сдвигайте этапы и меняйте длительность. Сроки и денежный поток пересчитываются. М1 =','months':'месяцев','Signed in as':'Вы вошли как','mo':'мес.','scenario':'сценарий','total development sales':'общая выручка от продаж','of portfolio':'портфеля','Construction M':'Строительство М','· Salary payments M':'· Зарплата М','. All salaries are company expenses, without project allocation.':'. Все зарплаты — расходы компании без распределения по проектам.','Apply the migration in':'Примените миграцию из','Add the project URL and public anon key to':'Добавьте URL проекта и публичный anon key в',', then restart.':', затем перезапустите.'});
Object.assign(ru,{'Model start · M1':'Начало модели · М1','Model calendar':'Календарь модели','Dates follow the model start. Change it in the model header or Settings.':'Все даты считаются от начала модели. Изменить его можно в шапке или настройках.'});
Object.assign(ru,{'Allocated units':'Распределено юнитов','Matches the plan':'Совпадает с планом','Still to allocate':'Осталось распределить','Over plan':'Сверх плана'});
Object.assign(ru,{'Prices & sales mix':'Цены и типы продаж','Units by payment plan':'Распределение юнитов по типу оплаты','Set unit counts and buyer payment plans in the rows below. Each unit type must be fully allocated.':'В строках ниже задайте количество юнитов и тип оплаты покупателем. Для каждого типа юнитов сумма должна совпадать с планом.','Full cash or installments? Set the number of units for each payment plan in Prices & sales mix.':'Полная оплата или рассрочка? Укажите количество юнитов для каждого варианта во вкладке «Цены и типы продаж».','Edit sales mix':'Настроить типы продаж'});
Object.assign(ru,{'Income / positive result':'Доходы / положительный результат','Expenses / losses':'Расходы / убытки','Funding requirement':'Потребность в финансировании'});
Object.assign(ru,{'% of revenue':'% от выручки','% of revenue = line amount ÷ contracted revenue for the selected scope. No percentage is shown when revenue is zero.':'% от выручки = сумма статьи ÷ выручка по договорам выбранного проекта или портфеля. При нулевой выручке процент не рассчитывается.'});
Object.assign(ru,{'Rate · %':'Ставка · %','Calculation for this project':'Расчёт по этому проекту','Contracted revenue':'Выручка по договорам','Scenario adjustment':'Поправка сценария','Uses the same sales plan as P&L. Portfolio percentages combine the amounts and revenues of all projects.':'Используется тот же план продаж, что и в P&L. Процент по портфелю считается из сумм затрат и выручки всех проектов.'});

Object.assign(ru,{'PBG starts after land control / payment':'PBG начинается после контроля / оплаты земли'});

Object.assign(ru,{'Developer name':'Название девелопера','Edit developer name':'Изменить название девелопера'});
Object.assign(ru,{'Start month':'Месяц начала','Start year':'Год начала'});
Object.assign(ru,{'Editing access':'Доступ к редактированию','Refresh':'Обновить','No access requests yet.':'Запросов на доступ пока нет.','Allow editing':'Разрешить редактирование','Revoke access':'Отозвать доступ','Decline':'Отклонить','pending':'Ожидает решения','approved':'Доступ разрешён','rejected':'Доступ закрыт','Access updated.':'Доступ обновлён.','Access management requires the collaboration migration.':'Для управления доступом примените миграцию совместной работы в Supabase.','View only · original model is protected':'Только просмотр · исходная модель защищена','Make an editable copy':'Создать редактируемую копию','Edit original':'Редактировать оригинал','Request editing access':'Запросить редактирование','Check access':'Проверить доступ','Sign in, then return to this page to request editing access.':'Войдите в аккаунт, затем вернитесь сюда, чтобы запросить редактирование.','Access granted.':'Доступ разрешён.','Request sent. The model owner can approve it in Share.':'Запрос отправлен. Владелец может одобрить его в разделе «Поделиться».','Access is unavailable.':'Доступ недоступен.','A copy is saved on this device. Sign in and save it to cloud to use it on other devices.':'Копия сохраняется на этом устройстве. Войдите и сохраните её в облако, чтобы открыть на других устройствах.'});

Object.assign(ru,{'Cloud models loaded. Previous local versions are preserved in Version history.':'Модели загружены из облака. Предыдущие локальные версии сохранены в истории версий.','Before cloud load':'Перед загрузкой из облака'});

Object.assign(ru,{'Remove model':'Удалить модель','Keep at least one model':'Должна остаться хотя бы одна модель','Remove this model from this device? A recoverable copy stays in Trash. The cloud copy is kept.':'Убрать модель с этого устройства? Её можно будет восстановить из корзины. Облачная копия сохранится.','Model moved to Trash.':'Модель перемещена в корзину.','Trash':'Корзина','Trash is stored on this device. Cloud loading will not restore these models automatically.':'Корзина хранится на этом устройстве. При загрузке из облака эти модели не вернутся в список автоматически.','Model restored.':'Модель восстановлена.'});

Object.assign(ru,{'Create copy':'Создать копию','Copy':'Копия','Copy created on this device. Save it to cloud in Settings to use it on other devices.':'Копия создана на этом устройстве. Сохраните её в облако в настройках, чтобы открыть на других устройствах.'});

Object.assign(ru,{'Timeline sales period':'Период продаж в таймлайне','Green: sales period. Grey: outside the timeline period.':'Зелёным — период продаж. Серым — месяцы за его пределами.','Units outside the timeline sales period':'Юнитов за пределами периода продаж','Move these sales or adjust the Sales stage in the timeline.':'Перенесите эти продажи или измените этап «Продажи» в таймлайне.','Sales period':'Период продаж','Outside period':'Вне периода'});

Object.assign(ru,{'Sales start':'Старт продаж','Sales end':'Конец продаж'});

Object.assign(ru,{'60% sold':'Продано 60%','60% sold — start a new project':'Продано 60% — старт нового проекта','Based on cumulative contracted units across the portfolio, not payments received.':'По накопленным продажам юнитов всего портфеля, а не по полученным платежам.','New project milestone: 60% of portfolio units have not been sold in this plan.':'Старт нового проекта: в этом плане порог продажи 60% юнитов портфеля ещё не достигнут.'});

Object.assign(ru,{'View only · this financial model only':'Только просмотр этой финансовой модели','Only this model is shared for 7 days. The viewer has no editing, copying, sign-in or workspace navigation controls. The link shows the latest cloud-saved version.':'Ссылка на 7 дней открывает только эту модель. Без кнопок редактирования, копирования, входа и перехода к другим моделям. По ссылке отображается последняя сохранённая в облаке версия.','Save the latest changes to this model in the cloud before creating a viewing link.':'Сначала сохраните последние изменения этой модели в облако, затем создайте ссылку для просмотра.','Link created. It expires in 7 days.':'Ссылка создана. Срок действия — 7 дней.','This link has expired or is unavailable.':'Срок действия ссылки истёк или она недоступна.','Loading shared model…':'Загрузка модели…'});

Object.assign(ru,{'Project margins exclude company overhead and payroll.':'Маржа проектов указана без общих затрат компании и фонда оплаты труда.','GLA m²':'Полезная площадь, м²','Unit mix & pricing':'Типы юнитов и цены','Work period':'Период работы','Monthly salary':'Зарплата в месяц'});

Object.assign(ru,{'Only this model is shared for 7 days. The viewer can browse this model’s interactive pages without editing, copying or accessing other models. The link shows the latest cloud-saved version.':'Ссылка на 7 дней открывает интерактивный сайт одной модели: обзор, проекты, графики и таблицы. Без редактирования, копирования и доступа к другим моделям. Отображается последняя облачная версия.'});

Object.assign(ru,{'Save this model to cloud':'Сохранить изменения в облако','Please wait…':'Подождите…','This model is saved to cloud. You can now create a viewing link.':'Модель сохранена в облако. Теперь можно создать ссылку для просмотра.','Could not save the model. Your local changes are retained.':'Не удалось сохранить модель в облако. Локальные изменения сохранены.','Sign in with a verified email to save changes.':'Для сохранения войдите с подтверждённым email.'});

Object.assign(ru,{'Section':'Раздел'});

Object.assign(ru,{'Percentages of total revenue':'Проценты от общей выручки','of revenue':'от выручки'});

Object.assign(ru,{'Show villa':'Шоу-вилла','Add show villa':'Добавить шоу-виллу','Remove show villa':'Убрать шоу-виллу','Select unit type':'Выберите тип юнита','One existing unit, built on a separate schedule. Its budget is included in total construction costs.':'Один из существующих юнитов с отдельным графиком строительства. Его бюджет включён в общие затраты на стройку.','Show villa start · model month':'Старт шоу-виллы · месяц модели','Show villa duration · months':'Срок стройки шоу-виллы · месяцев','Budget within total construction':'Бюджет в составе общей стройки','Independent start. Advanced budget is allocated by unit area.':'Старт независимый. Расширенный бюджет распределяется пропорционально площади юнита.'});

Object.assign(ru,{'≥70% sold · positive cash flow':'Продано ≥70% · поток в плюсе','70% sold + positive cash flow — start a new project':'Продано ≥70%, поток в плюсе — старт нового проекта','First month with at least 70% of portfolio units contracted and positive cumulative cash flow.':'Первый месяц, когда продано не менее 70% юнитов портфеля и накопленный денежный поток положительный.','New project milestone not reached: at least 70% sold and positive cumulative cash flow are required.':'Условия старта нового проекта пока не достигнуты: нужны продажи не менее 70% юнитов и положительный накопленный денежный поток.'});

Object.assign(ru,{'View and create own copy':'Просмотр и создание своей копии','Invite by email. After verification, your friend can view this model and edit an independent copy. The original stays read-only.':'Укажите email друга. После подтверждения почты он увидит эту модель и сможет редактировать собственную копию. Оригинал доступен только для чтения.','Friend’s email':'Email друга','Grant access':'Предоставить доступ','Copy invited models link':'Скопировать ссылку для приглашённого','Models shared with me':'Доступные мне модели','My workspace':'Мои модели','Create my editable copy':'Создать свою копию','Originals are read-only. Your copies are saved separately in your account.':'Оригиналы доступны только для чтения. Ваши копии сохраняются отдельно в вашем аккаунте.','No invitations for this email yet.':'Для этого email пока нет приглашений.','View model':'Посмотреть модель','Sign in with the verified email used in your invitation.':'Войдите с подтверждённым email, на который вам предоставили доступ.','Access granted. Send your friend the invited models link. No email is sent automatically.':'Доступ предоставлен. Отправьте другу ссылку для приглашённого. Письмо автоматически не отправляется.','Access revoked. Existing independent copies are retained.':'Доступ отозван. Уже созданные независимые копии сохраняются.','Invitation access is not available yet.':'Приглашения пока недоступны.','Loading…':'Загрузка…'});
