import {describe,it,expect} from 'vitest';
import {demoModel} from '@/lib/demo';
import {migrateWorkforce,copyProjectStaff,removeProjectStaff} from '@/lib/workforce';
import {neutral} from '@/types/model';
import {modelEnvelope} from '@/lib/validation/model';
import {calculatePortfolioCashFlow,calculateProjectCashFlow,calculateCorporateOverhead,allocateSharedResources,calculateWorkforcePayroll,departmentWindow,moveDepartment} from './index';
const sum=(rows:{amount:number}[])=>rows.reduce((a,x)=>a+x.amount,0);
describe('central employee directory',()=>{
it('migrates all nine employees into four company departments, clearing salary duplicates',()=>{const m=migrateWorkforce(demoModel());expect(m.workforce!.employees).toHaveLength(9);expect(m.workforce!.departments).toHaveLength(4);expect(m.workforce!.employees.some(e=>e.role==='CEO')).toBe(true);expect(m.projects.every(p=>p.payroll.length===0)).toBe(true);expect(m.corporate.some(c=>c.name==='CEO')).toBe(false);expect(m.resources).toHaveLength(0);expect(modelEnvelope.safeParse(m).success).toBe(true)});
it('migration preserves every monthly cash balance and the lifetime budget',()=>{const legacy=demoModel(),m=migrateWorkforce(legacy),r=calculatePortfolioCashFlow(m);const ps=legacy.projects.map(p=>calculateProjectCashFlow(p));const other=[...calculateCorporateOverhead(legacy),...allocateSharedResources(legacy)];r.months.forEach((v,i)=>expect(v.outflow).toBeCloseTo(ps.reduce((s,p)=>s+(p.months[i]?.outflow||0),0)+sum(other.filter(x=>x.month===i+1)),2));expect(r.costs.Payroll).toBe(372000);expect(r.cost).toBe(5432200)});
it('is pure and idempotent; keeps source salaries and non-staff operating costs',()=>{const old=demoModel(),saved=JSON.stringify(old);const m=migrateWorkforce(old);expect(JSON.stringify(old)).toBe(saved);expect(migrateWorkforce(m)).toBe(m);expect(m.corporate.some(c=>c.name==='Office Rent')).toBe(true);expect(m.workforce!.employees.find(e=>e.role==='CEO')!.salary).toBe(5000)});
it('pays employees only within inclusive department dates',()=>{const m=migrateWorkforce(demoModel()),d=m.workforce!.departments.find(d=>d.name==='Management')!;d.offset=5;d.duration=3;const rows=calculateWorkforcePayroll(m).filter(r=>r.departmentId===d.id);expect(rows.map(r=>r.month)).toEqual([6,7,8]);expect(sum(rows)).toBe(15000)});
it('moving a department changes cash timing, not salary budget',()=>{const m=migrateWorkforce(demoModel()),d=m.workforce!.departments.find(d=>d.name==='Management')!;const moved=moveDepartment(m,d.id,2);expect(departmentWindow(moved,moved.workforce!.departments.find(x=>x.id===d.id)!)).toEqual({start:3,end:14,duration:12});expect(calculatePortfolioCashFlow(moved).cost).toBe(calculatePortfolioCashFlow(m).cost);expect(calculatePortfolioCashFlow(moved).months[0].outflow).toBe(calculatePortfolioCashFlow(m).months[0].outflow-5000)});
it('resizing the end recalculates all salaries in the department',()=>{const m=migrateWorkforce(demoModel()),d=m.workforce!.departments.find(d=>d.name==='Construction')!;const resized=moveDepartment(m,d.id,2,'end');expect(calculatePortfolioCashFlow(resized).cost-calculatePortfolioCashFlow(m).cost).toBe(42000)});
it('left resize cannot invert a department or move it before month 1',()=>{const m=migrateWorkforce(demoModel()),d=m.workforce!.departments[0];const moved=moveDepartment(m,d.id,-200,'start');const next=moved.workforce!.departments[0];expect(departmentWindow(moved,next).start).toBe(1);const resized=moveDepartment(m,d.id,200,'start');expect(resized.workforce!.departments[0].duration).toBe(1)});
it('department payroll follows PBG and construction dependency changes',()=>{const m=migrateWorkforce(demoModel()),d=m.workforce!.departments.find(d=>d.name==='Construction')!;expect(departmentWindow(m,d).start).toBe(5);expect(departmentWindow(m,d,{...neutral,pbgDelay:3}).start).toBe(8);expect(sum(calculateWorkforcePayroll(m,{...neutral,pbgDelay:3}))).toBeCloseTo(372000,2)});
it('project deletion and duplication leave company staff unchanged',()=>{const m=migrateWorkforce(demoModel()),source=m.projects[0].id,target=crypto.randomUUID();const copy=copyProjectStaff(m,source,target,()=>crypto.randomUUID());expect(copy.workforce!.employees.length).toBe(9);expect(copy.workforce!.employees.filter(e=>e.role==='CEO').length).toBe(1);const removed=removeProjectStaff(m,source);expect(removed.workforce!.employees.length).toBe(9)});
it('allocation does not lose salary when no projects exist',()=>{const m=migrateWorkforce(demoModel());m.projects=[];expect(sum(calculateWorkforcePayroll(m))).toBe(372000)});
});

it('charges every salary to the company and none to projects',()=>{const m=migrateWorkforce(demoModel());expect(m.workforce!.departments.every(d=>d.projectId===null&&d.allocation==='Corporate')).toBe(true);expect(calculateWorkforcePayroll(m).every(r=>r.projectId===null)).toBe(true);const r=calculatePortfolioCashFlow(m);expect(r.costs.Payroll).toBe(372000);expect(r.projects.every(p=>!p.costs.Payroll)).toBe(true);m.workforce!.departments[0].projectId=m.projects[0].id;m.workforce!.departments[0].allocation='By Revenue';expect(calculateWorkforcePayroll(m).every(r=>r.projectId===null)).toBe(true)});
