'use client';
import {PieChart,Pie,Cell,ResponsiveContainer,Tooltip} from 'recharts';
import {Result} from '@/types/model';
import {tr} from '@/lib/i18n';
import {groupCosts} from '@/lib/cost-groups';
export function EconomicsChart({result:r,currency,projectName,includesCompany=false}:{result:Result;currency:string;projectName?:string;includesCompany?:boolean}){
 const money=(n:number)=>new Intl.NumberFormat('ru-RU',{style:'currency',currency,maximumFractionDigits:0}).format(n);
 const costs=groupCosts(r.costs);
 const data=[...(r.profit>0?[{name:'Прибыль',value:r.profit,color:'#34a879'}]:[]),...costs];
 const percent=(n:number)=>r.revenue>0?(n/r.revenue*100).toFixed(1)+'%':'—';
 return <section className="v-card v-economics"><div className="v-section-title"><div><h2>Структура выручки</h2><p>{projectName||'Весь портфель'} · {includesCompany?'затраты проекта и компании, включая ФОТ':projectName?'затраты проекта':'затраты проектов и компании'} · до финансирования и выплат инвесторам</p></div><span className="v-economics-margin">Маржа <b className={r.profit<0?'negative':''}>{percent(r.profit)}</b></span></div><div className="v-economics-grid"><div className="v-economics-ring">{data.length>0?<ResponsiveContainer width="100%" height={310}><PieChart><Pie data={data} dataKey="value" nameKey="name" innerRadius="68%" outerRadius="90%" paddingAngle={1} isAnimationActive={false}>{data.map((entry,i)=><Cell key={i} fill={entry.color}/>)}</Pie><Tooltip formatter={v=>money(Number(v))}/></PieChart></ResponsiveContainer>:<div className="v-economics-empty"/>}<div className="v-economics-center"><span>Выручка</span><strong>{money(r.revenue)}</strong></div></div><div className="v-economics-breakdown"><div className="v-economics-labels"><span>Блок</span><span>Сумма</span><span>% выручки</span></div>{r.profit>0&&<div className="v-economics-row"><span><i style={{background:'#34a879'}}/>Прибыль</span><b>{money(r.profit)}</b><span>{percent(r.profit)}</span></div>}{costs.map(group=><details className="v-cost-group" key={group.id}><summary className="v-economics-row"><span><i style={{background:group.color}}/><span className="v-cost-chevron">›</span>{group.name}</span><b>{money(group.value)}</b><span>{percent(group.value)}</span></summary><div className="v-cost-items">{group.items.map(item=><div className="v-economics-row" key={item.name}><span>{tr(item.name)}</span><b>{money(item.value)}</b><span>{percent(item.value)}</span></div>)}</div></details>)}{r.profit<=0&&<div className="v-economics-row negative"><span>{r.profit<0?'Убыток':'Прибыль'}</span><b>{money(r.profit)}</b><span>{percent(r.profit)}</span></div>}<div className="v-economics-row v-economics-total"><span>Всего затрат</span><b>{money(r.cost)}</b><span>{percent(r.cost)}</span></div></div></div><p className="v-note">Нажмите на группу, чтобы увидеть её статьи. Неопознанные статьи собраны в «Прочие расходы». </p><p className="v-note">{r.profit<0?'Затраты превышают выручку. Кольцо показывает структуру затрат; проценты в таблице рассчитаны от выручки и в сумме превышают 100%.':r.revenue<=0?'Выручка не задана: доли от выручки пока не рассчитываются. Кольцо показывает структуру затрат.':'Выручка = затраты + прибыль. Доля прибыли в выручке — это маржа; остальные доли показывают расходы по блокам.'}</p></section>;
}
