'use client';
import {tr,useLanguage} from '@/lib/i18n';
import {Project} from '@/types/model';
import {Field,Select} from '@/components/ui/controls';
import {landAreaAre,leaseholdQuote} from '@/lib/land-price';
import {money,number} from '@/lib/format';
export function LandPricing({project:p,onChange}:{project:Project;onChange:(patch:Partial<Project['land']>)=>void}){useLanguage();
 const l=p.land,mode=l.pricingMode||'Manual',lease=l.leasehold||{years:25,pricePerAreYearIdr:0,idrPerUsd:0},quote=leaseholdQuote(l);
 return <section className="land-pricing"><div className="form-grid"><Select label={tr("Land price calculation")} value={mode} options={p.currency==='USD'?['Manual','Leasehold']:['Manual']} onChange={pricingMode=>onChange(pricingMode==='Leasehold'?{pricingMode,area:landAreaAre(l),unit:'are',leasehold:lease}:{pricingMode})}/>{mode==='Manual'?<><Field label={tr("Land area")} type="number" value={l.area} onChange={area=>onChange({area})}/><Select label={tr("Area unit")} value={l.unit} options={['are','m²','hectare']} onChange={unit=>onChange({unit})}/><Field label={`Land total cost · ${p.currency}`} type="number" value={l.cost} onChange={cost=>onChange({cost})}/></>:<><Field label={tr("Leasehold term · years")} type="number" min={1} max={999} value={lease.years} onChange={years=>onChange({leasehold:{...lease,years}})}/><Field label={tr("Land area · are / сотки")} help={tr("1 are = 1 сотка = 100 m²")} type="number" value={landAreaAre(l)} onChange={area=>onChange({area,unit:'are'})}/><Field label={tr("Price per are per year · IDR")} type="number" value={lease.pricePerAreYearIdr} onChange={pricePerAreYearIdr=>onChange({leasehold:{...lease,pricePerAreYearIdr}})}/><Field label={tr("Exchange rate · IDR per 1 USD")} help={tr("Your model assumption; no live rate is applied.")} type="number" value={lease.idrPerUsd} onChange={idrPerUsd=>onChange({leasehold:{...lease,idrPerUsd}})}/></>}</div>{mode==='Leasehold'&&<div className="notice"><strong>{tr("Land total · USD: ")}{quote?money(quote.usd,false,'USD'):'Enter exchange rate'}</strong><p>{tr(quote?`${number(lease.years)} years × ${number(landAreaAre(l))} are × ${number(lease.pricePerAreYearIdr)} IDR = ${number(quote.idr)} IDR ÷ ${number(lease.idrPerUsd)} IDR/USD`:`Until the exchange rate is entered, the model uses the manual price of ${money(l.cost,false,p.currency)}.`)}</p>{l.type==='Custom Schedule'&&<p>{tr("Custom payment amounts are entered separately and must match the calculated total.")}</p>}</div>}{p.currency!=='USD'&&<p className="department-hint">{tr("The IDR → USD leasehold calculator is available for projects in USD.")}</p>}</section>
}
