'use client';
import {ProjectSchedule} from './project-schedule';
import {UnitSalesEditor} from './unit-sales-editor';
import {CostCalculation} from './cost-calculation';
import {tr,useLanguage} from '@/lib/i18n';
import {LandPricing} from '@/features/projects/land-pricing';
import {landPrice} from '@/lib/land-price';
import {modelMonthDate,modelMonthLabel} from '@/lib/model-calendar';
import {useState,useEffect,useRef} from 'react';
import {useForm} from 'react-hook-form';
import {zodResolver} from '@hookform/resolvers/zod';
import {Plus,Trash2,ChevronRight,ChevronLeft} from 'lucide-react';
import {Project,Adjustments,neutral} from '@/types/model';
import {Field,Select,Toggle} from '@/components/ui/controls';
import {id} from '@/lib/demo';
import {InfrastructureEditor} from './infrastructure-editor';
import {ShowVilla} from './show-villa';
import {timeline,calculateProjectCashFlow,calculateLandPayments,calculateConstructionSpend} from '@/lib/financial-engine';
import {money as formatMoney,number} from '@/lib/format';
import {projectGeneralSchema} from '@/lib/validation/model';
export const steps=['Basic','Land','Timeline','Sales','Construction','Infrastructure','Costs'];
const labels:Record<string,string>={Basic:'Проект',Land:'Земля',Timeline:'Сроки',Sales:'Юниты и продажи',Construction:'Строительство',Infrastructure:'Инфраструктура',Costs:'Прочие затраты'};
const descriptions:Record<string,string>={Basic:'Название, локация и валюта проекта',Land:'Стоимость участка и порядок оплаты',Timeline:'Календарь строительства и продаж',Sales:'Площади, цены, оплаты и помесячный план',Construction:'Себестоимость и график расходов',Infrastructure:'Объекты с отдельным бюджетом',Costs:'Разрешения, комиссии, налоги и резерв'};
export function ProjectEditor({project,onChange,initial='Basic',startDate,a=neutral,wizard=false,onDone}:{project:Project;onChange:(p:Project)=>void;initial?:string;startDate:string;a?:Adjustments;wizard?:boolean;onDone?:()=>void}){useLanguage();const [tab,setTab]=useState(['Unit Mix','Pricing'].includes(initial)?'Sales':initial);const bodyRef=useRef<HTMLDivElement>(null);useEffect(()=>{bodyRef.current?.scrollTo({top:0,left:0})},[tab]);const p=project;const money=(n:number,c=false)=>formatMoney(n,c,p.currency);const set=(patch:Partial<Project>)=>onChange({...p,...patch});const land=(patch:Partial<Project['land']>)=>set({land:{...p.land,...patch}});const con=(patch:Partial<Project['construction']>)=>set({construction:{...p.construction,...patch}});const t=timeline(p,a),r=calculateProjectCashFlow(p,a,36,startDate);const form=useForm({resolver:zodResolver(projectGeneralSchema),values:{name:p.name,location:p.location,country:p.country,type:p.type,status:p.status,start:p.start}});return <div className="project-editor"><aside className="pe-nav"><div className="pe-project"><small>ПРОЕКТ</small><strong>{p.name}</strong></div><nav aria-label="Разделы проекта">{steps.map((step,i)=><button key={step} className={step===tab?'active':''} aria-current={step===tab?'page':undefined} onClick={()=>setTab(step)}><span>{String(i+1).padStart(2,'0')}</span>{labels[step]}</button>)}</nav><div className="pe-calendar"><small>Календарь модели</small><strong>{tr(modelMonthLabel(startDate,1))}</strong><span>Изменения сохраняются сразу</span></div></aside><div className="pe-body" ref={bodyRef}><header className="pe-heading"><div><h2>{labels[tab]}</h2><p>{descriptions[tab]}</p></div><div className="pe-live"><span>Выручка · сценарий<strong>{money(r.revenue,true)}</strong></span><span>Маржа проекта<strong>{(r.margin*100).toFixed(1)}%</strong></span></div></header><div className="pe-panel" key={tab}>

{tab==='Basic'&&<form className="form-grid" onSubmit={form.handleSubmit(v=>set(v))}><label className="field"><span>{tr("Project name")}</span><input {...form.register('name',{onChange:e=>set({name:e.target.value})})}/>{form.formState.errors.name&&<small>{form.formState.errors.name.message}</small>}</label><Field label={tr("Location")} value={p.location} onChange={location=>set({location})}/><Field label={tr("Country")} value={p.country} onChange={country=>set({country})}/><Select label={tr("Project type")} value={p.type} options={['Villa','Apartment','Townhouse','Hotel','Mixed']} onChange={type=>set({type})}/><Select label={tr("Status")} value={p.status} options={['Hypothesis','Land Selected','Land Secured','PBG','Construction','Sales','Completed']} onChange={status=>set({status})}/><label className="field"><span>Начало проекта</span><input type="month" value={modelMonthDate(startDate,p.start).toISOString().slice(0,7)} min={startDate.slice(0,7)} onChange={e=>{if(!e.target.value)return;const [y,m]=e.target.value.split('-').map(Number),[by,bm]=startDate.split('-').map(Number);set({start:Math.max(1,Math.min(120,(y-by)*12+m-bm+1))})}}/></label><Select label={tr("Currency · match portfolio reporting")} value={p.currency} options={['USD','IDR','EUR','GBP','AUD','SGD']} onChange={currency=>set({currency})}/></form>}
{tab==='Land'&&<><LandPricing project={p} onChange={land}/><div className="form-grid"><Select label={tr("Payment type")} value={p.land.type} options={['Full Payment','Installments','Custom Schedule']} onChange={type=>land({type})}/><Field label={tr("Land control · project month")} type="number" min={1} step={1} value={p.land.control} onChange={control=>land({control})}/>{p.land.type==='Installments'&&<><Field label={tr("Down payment · %")} type="number" max={100} value={p.land.down} onChange={down=>land({down})}/><Field label={tr("Installment count")} type="number" min={1} max={120} step={1} value={p.land.count} onChange={count=>land({count})}/><Field label={tr("Frequency · months")} type="number" min={1} max={12} step={1} value={p.land.frequency} onChange={frequency=>land({frequency})}/><Field label={tr("First installment · project month")} type="number" min={1} step={1} value={p.land.first} onChange={first=>land({first})}/></>}</div><Toggle label={tr("PBG may start after initial payment / land control")} checked={p.land.permitAfterInitial} onChange={permitAfterInitial=>land({permitAfterInitial})}/>{p.land.type==='Custom Schedule'&&<div className="stack">{p.land.custom.map((x,i)=><div className="row" key={i}><Field label={tr("Project month")} type="number" min={1} value={x.month} onChange={month=>land({custom:p.land.custom.map((v,j)=>j===i?{...v,month}:v)})}/><Field label={tr("Amount · $")} type="number" value={x.amount} onChange={amount=>land({custom:p.land.custom.map((v,j)=>j===i?{...v,amount}:v)})}/><button className="delete-btn" onClick={()=>land({custom:p.land.custom.filter((_,j)=>j!==i)})} aria-label={tr("Remove payment")}><Trash2 size={16}/></button></div>)}<button className="btn" onClick={()=>land({custom:[...p.land.custom,{month:1,amount:0}]})}><Plus size={14}/>{tr(" Add payment")}</button></div>}<div className="notice">{tr("Land control M")}{p.start+p.land.control-1}{tr(" · PBG starts M")}{t.pbgStart}{tr(" · Total scheduled ")}{money(calculateLandPayments(p,a).reduce((s,x)=>s+x.amount,0))}</div><div className="land-timeline">{calculateLandPayments(p,a).map((x,i)=><div key={i}><small>{tr("M")}{x.month}</small><i style={{height:Math.max(6,x.amount/Math.max(1,landPrice(p))*120)}}/><b>{money(x.amount,true)}</b></div>)}</div></>}
{tab==='Timeline'&&<ProjectSchedule project={p} startDate={startDate} onChange={onChange}/>}
{tab==='Sales'&&<UnitSalesEditor project={p} a={a} startDate={startDate} onChange={onChange}/>}
{tab==='Construction'&&<><ShowVilla project={p} a={a} onChange={construction=>set({construction})}/><div className="form-grid"><Select label={tr("Cost mode")} value={p.construction.mode} options={['Simple','Advanced']} onChange={mode=>con({mode})}/><Field label={tr("Construction cost / m² · $")} type="number" value={p.construction.costPerM2} onChange={costPerM2=>con({costPerM2})}/><button className="pe-date-link" onClick={()=>setTab('Timeline')}>Сроки строительства · {tr(modelMonthLabel(startDate,t.constructionStart))} — {tr(modelMonthLabel(startDate,t.completion))}</button><Select label={tr("Spend curve")} value={p.construction.curve} options={['Even','S-Curve','Front Loaded','Back Loaded','Custom']} onChange={curve=>con({curve})}/></div>{p.construction.mode==='Advanced'&&<div className="stack">{p.construction.items.map((x,i)=><div className="row" key={i}><Field label={tr("Construction category")} value={x.name} onChange={name=>con({items:p.construction.items.map((v,j)=>i===j?{...v,name}:v)})}/><Field label={tr("Budget · $")} type="number" value={x.amount} onChange={amount=>con({items:p.construction.items.map((v,j)=>i===j?{...v,amount}:v)})}/><button aria-label={tr("Remove construction category")} className="delete-btn" onClick={()=>con({items:p.construction.items.filter((_,j)=>i!==j)})}><Trash2 size={15}/></button></div>)}<button className="btn" onClick={()=>con({items:[...p.construction.items,{name:'Other',amount:0}]})}>{tr("Add construction category")}</button></div>}{p.construction.curve==='Custom'&&<Field label={tr("Monthly percentages · comma separated · total 100%")} value={p.construction.custom.join(', ')} onChange={v=>con({custom:String(v).split(',').map(x=>Math.max(0,Number(x)||0))})}/> }<div className="notice">{number(r.gla)}{tr(" m² × ")}{money(p.construction.costPerM2)}{tr(" / m² = ")}{money(calculateConstructionSpend(p,a).reduce((s,x)=>s+x.amount,0))} {p.construction.mode==='Advanced'&&'(advanced budget)'}{tr(" · M")}{t.constructionStart}–{t.completion}</div></>}
{tab==='Infrastructure'&&<InfrastructureEditor project={p} a={a} startDate={startDate} onChange={infrastructure=>set({infrastructure})}/>}
{tab==='Costs'&&<><div className="stack">{p.costs.map(c=><div className="editor-section" key={c.id}><div className="row spread"><h3>{c.name}</h3><button className="delete-btn" aria-label={tr("Remove development cost")} onClick={()=>set({costs:p.costs.filter(x=>x.id!==c.id)})}><Trash2 size={16}/></button></div><div className="form-grid">{(['name','amount','driver','timing','start','duration'] as const).filter(key=>(key!=='start'&&key!=='duration')||c.timing==='Custom').map(key=>{const upd=(value:any)=>set({costs:p.costs.map(x=>x.id===c.id?{...x,[key]:value}:x)});return key==='driver'?<Select key={key} label={tr("Cost driver")} value={c.driver} options={['Fixed $','$ / unit','$ / m²','% Revenue','% Construction']} onChange={upd}/>:key==='timing'?<Select key={key} label={tr("Timing")} value={c.timing} options={['Month 1','During PBG','Before Sales','During Sales','During Construction','At Handover','Custom','Timeline Stage']} onChange={upd}/>:<Field key={key} label={key==='start'?'Custom start · model month':key==='duration'?'Custom duration':key==='amount'?(c.driver.startsWith('%')?'Rate · %':`Сумма · ${p.currency}`):key==='name'?'Название статьи':key} value={c[key]} type={key==='name'?'text':'number'} min={key==='duration'||key==='start'?1:0} onChange={upd}/>})}{c.timing==='Timeline Stage'&&<Select label={tr("Linked timeline stage")} value={c.stage||''} options={['',...p.timeline.stages.map(s=>s.name)]} onChange={stage=>set({costs:p.costs.map(x=>x.id===c.id?{...x,stage}:x)})}/>}</div><CostCalculation cost={c} project={p} adjustments={a}/></div>)}</div><button className="btn" onClick={()=>set({costs:[...p.costs,{id:id(),name:'Other',amount:0,driver:'Fixed $',timing:'Month 1',start:1,duration:1}]})}><Plus size={14}/>{tr(" Add development cost")}</button></>}
{r.warnings.length>0&&<details className="editor-section"><summary>{r.warnings.length}{tr(" model warnings")}</summary>{r.warnings.map((w,i)=><div className="warning" key={i}>{w}</div>)}</details>}{wizard&&<footer className="wizard-footer"><button className="btn" disabled={tab===steps[0]} onClick={()=>setTab(steps[Math.max(0,steps.indexOf(tab)-1)])}><ChevronLeft size={14}/>{tr(" Back")}</button>{tab!==steps.at(-1)?<button className="btn dark" onClick={()=>setTab(steps[steps.indexOf(tab)+1])}>{tr("Continue ")}<ChevronRight size={14}/></button>:<button className="btn dark" onClick={onDone} disabled={!p.name.trim()}>{tr("Create project")}</button>}</footer>}</div></div></div>}