'use client';
import {AppSelect} from '@/components/ui/app-select';
import {useState} from 'react';
import {Plus,Trash2} from 'lucide-react';
import {Project,Tier,UnitType,Adjustments,Curve} from '@/types/model';
import {Field,Select} from '@/components/ui/controls';
import {NumberInput} from '@/components/ui/number-input';
import {id} from '@/lib/demo';
import {calculateSalesPlan,timeline,projectWindow} from '@/lib/financial-engine';
import {baseTierMonths,changeTierCurve,tierMode} from '@/lib/project-editor';
import {modelMonthLabel} from '@/lib/model-calendar';
import {money,number} from '@/lib/format';
import {tr} from '@/lib/i18n';
import {ScheduleBar,ScheduleAxis} from './schedule-bar';
const curves:[Curve|'MANUAL',string][]=[['Even','Равномерно'],['S-Curve','S-кривая'],['Front Loaded','Больше в начале'],['Back Loaded','Больше в конце'],['Custom','Свои веса'],['MANUAL','Вручную по месяцам']];
const newTier=(units=0):Tier=>({id:id(),name:'Основные продажи',price:0,units,offset:0,window:12,manual:[],plan:{type:'Full Cash',down:100,maxTerm:12,finish:'Construction Completion',fixedMonth:24,custom:[]},schedule:{mode:'AUTO',curve:'Even',custom:[]}});
export function UnitSalesEditor({project:p,a,startDate,onChange}:{project:Project;a:Adjustments;startDate:string;onChange:(p:Project)=>void}){
 const [selected,setSelected]=useState(p.units[0]?.id),u=p.units.find(u=>u.id===selected)||p.units[0],sales=calculateSalesPlan(p,a),t=timeline(p),fmt=(n:number)=>money(n,false,p.currency);
 const setUnit=(uid:string,patch:Partial<UnitType>)=>onChange({...p,units:p.units.map(u=>u.id===uid?{...u,...patch}:u)});
 const setTier=(tid:string,patch:Partial<Tier>)=>setUnit(u.id,{tiers:u.tiers.map(t=>t.id===tid?{...t,...patch}:t)});
 function add(){const unit:UnitType={id:id(),name:'Новый тип',quantity:1,area:60,tiers:[newTier(1)]};onChange({...p,units:[...p.units,unit]});setSelected(unit.id)}
 return <div className="pe-sales"><p className="pe-help">Количество, цены и темп продаж — в одной карточке. Выручка в сводке учитывает выбранный сценарий и сезонность.</p>
 <div className="pe-unit-list">{p.units.map(unit=>{const rows=sales.filter(s=>unit.tiers.some(t=>t.id===s.tier.id)),sold=rows.reduce((s,r)=>s+r.units,0),value=rows.reduce((s,r)=>s+r.value,0);return <button className={`pe-unit-chip ${u?.id===unit.id?'active':''}`} key={unit.id} onClick={()=>setSelected(unit.id)}><strong>{unit.name}</strong><span>{unit.quantity} юнитов · {number(unit.area*unit.quantity)} м²</span><b>{fmt(value)}</b><small>В плане: {sold} из {unit.quantity}</small></button>})}<button className="pe-unit-add" onClick={add}><Plus size={20}/>Добавить тип</button></div>
 {!u?<div className="pe-empty">Добавьте первый тип юнитов, чтобы настроить площади, цены и продажи.</div>:<>
 <div className="pe-section-head"><div><h3>{u.name}</h3><p>Параметры одного юнита и объём проекта</p></div><button className="delete-btn" aria-label={`Удалить тип ${u.name}`} onClick={()=>onChange({...p,units:p.units.filter(x=>x.id!==u.id)})}><Trash2 size={17}/></button></div>
 <div className="form-grid"><Field label="Название типа" value={u.name} onChange={name=>setUnit(u.id,{name})}/><Field label="Площадь одного юнита · м²" value={u.area} type="number" min={1} onChange={area=>setUnit(u.id,{area})}/><Field label="Количество юнитов" value={u.quantity} type="number" step={1} onChange={quantity=>setUnit(u.id,{quantity})}/></div>
 {u.quantity!==u.tiers.reduce((n,t)=>n+t.units,0)&&<p className="pe-alert" role="status">{u.quantity-u.tiers.reduce((n,t)=>n+t.units,0)>0?'Осталось распределить':'Распределено сверх количества'}: {Math.abs(u.quantity-u.tiers.reduce((n,t)=>n+t.units,0))} юнитов. Укажите количество в группах продаж ниже.</p>}
 {u.tiers.map((tier,tierIndex)=>{const mode=tierMode(p,tier),curve=mode==='MANUAL'?'MANUAL':tier.schedule?.curve||p.salesCurve,monthly=baseTierMonths(p,tier),allocated=monthly.reduce((s,n)=>s+n,0),outside=monthly.reduce((s,n,i)=>s+((i+1<t.salesStart||i+1>=t.salesStart+t.salesDuration)?n:0),0),start=t.salesStart+tier.offset,end=start+tier.window-1,horizon=Math.max(end,projectWindow(p).end,monthly.findLastIndex(n=>n!==0)+1),highest=Math.max(1,...monthly),custom=tier.schedule?.custom||p.salesCustom;return <details className="pe-tier" key={tier.id} open={tierIndex===0}>
 <summary className="pe-section-head"><div><h3>{tier.name}</h3><p>{tier.units} юнитов × {fmt(tier.price)} = <strong>{fmt(tier.units*tier.price)}</strong> до сценарных поправок</p></div><button className="delete-btn" aria-label={`Удалить группу ${tier.name}`} onClick={e=>{e.preventDefault();setUnit(u.id,{tiers:u.tiers.filter(t=>t.id!==tier.id)})}}><Trash2 size={16}/></button></summary>
 <div className="form-grid"><Field label="Группа продаж" value={tier.name} onChange={name=>setTier(tier.id,{name})}/><Field label="Юнитов в группе" type="number" step={1} value={tier.units} onChange={units=>setTier(tier.id,{units})}/><Field label={`Цена за юнит · ${p.currency}`} type="number" value={tier.price} onChange={price=>setTier(tier.id,{price})}/></div>
 <details className="pe-details"><summary>Оплата покупателем · {tr(tier.plan.type)}{tier.plan.type==='Installment'?` · ${tier.plan.down}% первый взнос`:''}</summary><div className="form-grid"><Select label="Buyer payment plan" value={tier.plan.type} options={['Full Cash','Installment','Custom']} onChange={type=>setTier(tier.id,{plan:{...tier.plan,type}})}/>{tier.plan.type==='Installment'&&<><Field label="At signing · %" type="number" max={100} value={tier.plan.down} onChange={down=>setTier(tier.id,{plan:{...tier.plan,down}})}/><Field label="Maximum installment term" type="number" min={1} max={240} step={1} value={tier.plan.maxTerm} onChange={maxTerm=>setTier(tier.id,{plan:{...tier.plan,maxTerm}})}/><Select label="Finish payments by" value={tier.plan.finish} options={['Construction Completion','Handover','Fixed Date','No Restriction']} onChange={finish=>setTier(tier.id,{plan:{...tier.plan,finish}})}/>{tier.plan.finish==='Fixed Date'&&<Field label="Final payment · model month" type="number" min={1} max={240} step={1} value={tier.plan.fixedMonth} onChange={fixedMonth=>setTier(tier.id,{plan:{...tier.plan,fixedMonth}})}/>}</>}</div>{tier.plan.type==='Custom'&&<><p className="pe-help">Месяцы после подписания договора. Сумма платежей должна быть 100%.</p>{tier.plan.custom.map((payment,i)=><div className="row" key={i}><Field label="Месяцев после договора" type="number" step={1} max={240} value={payment.offset} onChange={offset=>setTier(tier.id,{plan:{...tier.plan,custom:tier.plan.custom.map((v,j)=>i===j?{...v,offset}:v)}})}/><Field label="Платёж · %" type="number" max={100} value={payment.percent} onChange={percent=>setTier(tier.id,{plan:{...tier.plan,custom:tier.plan.custom.map((v,j)=>i===j?{...v,percent}:v)}})}/><button className="delete-btn" aria-label="Удалить платёж" onClick={()=>setTier(tier.id,{plan:{...tier.plan,custom:tier.plan.custom.filter((_,j)=>j!==i)}})}><Trash2 size={16}/></button></div>)}<button className="btn" onClick={()=>setTier(tier.id,{plan:{...tier.plan,custom:[...tier.plan.custom,{offset:0,percent:Math.max(0,100-tier.plan.custom.reduce((n,x)=>n+x.percent,0))}]}})}>Добавить платёж</button></>}</details>
 <div className="pe-plan-heading"><div><h4>План продаж</h4><span>{allocated} из {tier.units} юнитов распределено</span></div><label className="field"><span>Кривая продаж</span><AppSelect aria-label={`Кривая продаж · ${tier.name}`} value={curve} onChange={e=>setTier(tier.id,changeTierCurve(p,tier,e.target.value as Curve|'MANUAL'))}>{curves.map(([value,label])=><option key={value} value={value}>{label}</option>)}</AppSelect></label></div>
 {mode==='AUTO'&&<div className="pe-schedule-scroll"><div className="pe-schedule-canvas"><ScheduleAxis horizon={horizon} startDate={startDate}/><ScheduleBar label={tier.name} start={start} duration={tier.window} horizon={horizon} startDate={startDate} color="#34a879" onChange={(next,duration)=>setTier(tier.id,{offset:Math.max(0,next-t.salesStart),window:duration})}/></div></div>}
 {mode==='MANUAL'&&<p className="pe-help">Укажите число продаж в каждом месяце. При переходе в ручной режим текущий базовый план переносится в таблицу.</p>}
 {curve==='Custom'&&<p className="pe-help">Задайте относительный вес каждого месяца. Юниты распределятся пропорционально весам; сумма весов может быть любой.</p>}
 {mode==='MANUAL'&&outside>0&&<p className="pe-alert">{outside} продаж вне общего периода продаж проекта. Проверьте месяцы или измените полосу «Продажи» в разделе «Сроки».</p>}
 {allocated!==tier.units&&<p className="pe-alert" role="status">{allocated<tier.units?'Не распределено':'Сверх плана'}: {Math.abs(tier.units-allocated)} юнитов.</p>}
 <div className="pe-month-scroll" role="region" aria-label={`Помесячные продажи · ${tier.name}`} tabIndex={0}><div className="pe-month-grid" style={{gridTemplateColumns:`repeat(${horizon},64px)`}}>{Array.from({length:horizon},(_,i)=>{const active=i+1>=start&&i+1<=end;return <div className={`pe-month ${active?'in-window':''}`} key={i}><div className="pe-month-bar"><i style={{height:`${Math.max(2,(monthly[i]||0)/highest*72)}px`}}/><b>{monthly[i]||0}</b></div><small>{tr(modelMonthLabel(startDate,i+1))}</small>{mode==='MANUAL'?<NumberInput aria-label={`${tier.name} · продажи · ${tr(modelMonthLabel(startDate,i+1))}`} min={0} max={100000} step={1} value={monthly[i]||0} onChange={e=>{const manual=Array.from({length:horizon},(_,j)=>monthly[j]||0);manual[i]=Math.max(0,Math.round(Number(e.target.value)||0));setTier(tier.id,{manual})}}/>:curve==='Custom'&&active?<NumberInput aria-label={`${tier.name} · вес · ${tr(modelMonthLabel(startDate,i+1))}`} min={0} value={custom[i+1-start]||0} onChange={e=>{const values=Array.from({length:tier.window},(_,j)=>custom[j]||0);values[i+1-start]=Math.max(0,Number(e.target.value)||0);setTier(tier.id,{schedule:{mode:'AUTO',curve:'Custom',custom:values}})}}/>:<span className="pe-month-value">{fmt((monthly[i]||0)*tier.price)}</span>}</div>})}</div></div>
 <p className="pe-help">Показан базовый план до сезонности и сценария.{mode==='MANUAL'?' Ручные продажи привязаны к календарным месяцам; перенос общей полосы продаж их не сдвигает.':''}</p>
 </details>})}
 <button className="btn" onClick={()=>setUnit(u.id,{tiers:[...u.tiers,{...newTier(Math.max(0,u.quantity-u.tiers.reduce((n,t)=>n+t.units,0))),window:t.salesDuration,name:'Новая группа'}]})}><Plus size={16}/>Добавить группу продаж</button>
 </>}
 </div>;
}
